-- Drive Learn VWCO
-- Vocabulário local para classificação dos relatos por sistema do veículo.
-- Execute após 20260729_019_master_categories_automotivas.sql.
-- Peso 10: expressão inequívoca; peso 1 a 4: termo de contexto.

SET NAMES utf8mb4;

DROP TEMPORARY TABLE IF EXISTS dl_category_terms_seed;
CREATE TEMPORARY TABLE dl_category_terms_seed (
    categoria_slug VARCHAR(140) NOT NULL,
    termo VARCHAR(120) NOT NULL,
    peso TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (categoria_slug,termo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO dl_category_terms_seed (categoria_slug,termo,peso) VALUES
('powertrain-desempenho','powertrain',10),
('powertrain-desempenho','perda de potência',10),
('powertrain-desempenho','sem força',9),
('powertrain-desempenho','baixo desempenho',9),
('powertrain-desempenho','perda de torque',9),
('powertrain-desempenho','consumo elevado',8),
('powertrain-desempenho','consumindo muito',8),
('powertrain-desempenho','não desenvolve',8),
('powertrain-desempenho','modo degradado',9),
('powertrain-desempenho','modo de emergência',9),

('motor','motor batendo',10),
('motor','falha no motor',10),
('motor','motor falhando',10),
('motor','pressão do óleo',10),
('motor','óleo do motor',8),
('motor','lubrificação',8),
('motor','fumaça azul',9),
('motor','fumaça branca',9),
('motor','fumaça preta',8),
('motor','não pega',7),
('motor','dificuldade na partida',8),
('motor','marcha lenta',7),
('motor','vazamento de óleo',9),

('transmissao-embreagem','transmissão',9),
('transmissao-embreagem','câmbio',9),
('transmissao-embreagem','caixa de câmbio',10),
('transmissao-embreagem','embreagem',10),
('transmissao-embreagem','troca de marcha',9),
('transmissao-embreagem','não engata',9),
('transmissao-embreagem','marcha não entra',10),
('transmissao-embreagem','tranco na troca',9),
('transmissao-embreagem','patinando',8),
('transmissao-embreagem','tomada de força',9),
('transmissao-embreagem','pto',8),

('sistema-arrefecimento','arrefecimento',10),
('sistema-arrefecimento','líquido de arrefecimento',10),
('sistema-arrefecimento','superaquecimento do motor',10),
('sistema-arrefecimento','temperatura do motor',10),
('sistema-arrefecimento','motor aquecendo',9),
('sistema-arrefecimento','radiador',9),
('sistema-arrefecimento','reservatório de expansão',9),
('sistema-arrefecimento','bomba d água',9),
('sistema-arrefecimento','ventoinha',8),
('sistema-arrefecimento','mangueira do radiador',9),
('sistema-arrefecimento','aditivo',6),
('sistema-arrefecimento','vazamento de água',8),

('sistema-combustivel','combustível',8),
('sistema-combustivel','injeção de combustível',10),
('sistema-combustivel','bomba de combustível',10),
('sistema-combustivel','filtro de combustível',9),
('sistema-combustivel','tanque de combustível',9),
('sistema-combustivel','vazamento de diesel',10),
('sistema-combustivel','diesel vazando',10),
('sistema-combustivel','bico injetor',9),
('sistema-combustivel','injetor',7),
('sistema-combustivel','água no diesel',9),
('sistema-combustivel','baixa pressão de combustível',10),

('admissao-turbo-exaustao','admissão de ar',9),
('admissao-turbo-exaustao','filtro de ar',8),
('admissao-turbo-exaustao','turbina',9),
('admissao-turbo-exaustao','turbo',8),
('admissao-turbo-exaustao','intercooler',9),
('admissao-turbo-exaustao','pressão do turbo',10),
('admissao-turbo-exaustao','mangueira do turbo',9),
('admissao-turbo-exaustao','escapamento',8),
('admissao-turbo-exaustao','coletor de escape',9),
('admissao-turbo-exaustao','vazamento de escape',9),

('pos-tratamento-emissoes','arla 32',10),
('pos-tratamento-emissoes','arla',9),
('pos-tratamento-emissoes','scr',9),
('pos-tratamento-emissoes','dpf',10),
('pos-tratamento-emissoes','filtro de partículas',10),
('pos-tratamento-emissoes','regeneração',9),
('pos-tratamento-emissoes','falha de emissões',10),
('pos-tratamento-emissoes','catalisador',8),
('pos-tratamento-emissoes','sensor de nox',10),
('pos-tratamento-emissoes','ureia',7),

('freios-retarder-freio-motor','sem freio',10),
('freios-retarder-freio-motor','perda de freio',10),
('freios-retarder-freio-motor','freio de serviço',10),
('freios-retarder-freio-motor','freio de estacionamento',9),
('freios-retarder-freio-motor','freio motor',9),
('freios-retarder-freio-motor','retarder',10),
('freios-retarder-freio-motor','abs',8),
('freios-retarder-freio-motor','ebs',8),
('freios-retarder-freio-motor','pastilha de freio',9),
('freios-retarder-freio-motor','lona de freio',9),
('freios-retarder-freio-motor','pedal de freio',8),
('freios-retarder-freio-motor','barulho ao frear',9),

('direcao','direção pesada',10),
('direcao','volante pesado',10),
('direcao','folga na direção',10),
('direcao','folga no volante',10),
('direcao','puxando para o lado',9),
('direcao','caixa de direção',10),
('direcao','coluna de direção',9),
('direcao','bomba hidráulica da direção',10),
('direcao','direção hidráulica',9),
('direcao','direção elétrica',9),
('direcao','volante torto',8),

('suspensao','suspensão',10),
('suspensao','bolsa de ar',9),
('suspensao','suspensão pneumática',10),
('suspensao','amortecedor',9),
('suspensao','mola quebrada',10),
('suspensao','feixe de molas',9),
('suspensao','veículo desnivelado',9),
('suspensao','não levanta',7),
('suspensao','válvula niveladora',10),
('suspensao','barra estabilizadora',9),

('chassi-eixos-diferencial','chassi trincado',10),
('chassi-eixos-diferencial','longarina',9),
('chassi-eixos-diferencial','travessa do chassi',9),
('chassi-eixos-diferencial','eixo traseiro',8),
('chassi-eixos-diferencial','eixo dianteiro',8),
('chassi-eixos-diferencial','diferencial',10),
('chassi-eixos-diferencial','cardã',10),
('chassi-eixos-diferencial','cruzeta',9),
('chassi-eixos-diferencial','redução do eixo',9),
('chassi-eixos-diferencial','tração 6x4',7),
('chassi-eixos-diferencial','tração 4x4',7),

('rodas-pneus','pneu furado',10),
('rodas-pneus','pneu estourou',10),
('rodas-pneus','desgaste do pneu',10),
('rodas-pneus','desgaste irregular',9),
('rodas-pneus','calibragem',8),
('rodas-pneus','pressão dos pneus',9),
('rodas-pneus','roda trincada',10),
('rodas-pneus','porca da roda',9),
('rodas-pneus','balanceamento',8),
('rodas-pneus','alinhamento',7),

('sistema-eletrico-alimentacao','bateria descarregada',10),
('sistema-eletrico-alimentacao','bateria 24v',9),
('sistema-eletrico-alimentacao','alternador',10),
('sistema-eletrico-alimentacao','motor de partida',10),
('sistema-eletrico-alimentacao','não dá partida',8),
('sistema-eletrico-alimentacao','fusível',8),
('sistema-eletrico-alimentacao','relé',8),
('sistema-eletrico-alimentacao','chicote elétrico',9),
('sistema-eletrico-alimentacao','curto circuito',10),
('sistema-eletrico-alimentacao','sem energia',8),
('sistema-eletrico-alimentacao','tensão baixa',9),

('eletronica-sensores-redes','falha eletrônica',9),
('eletronica-sensores-redes','sensor com defeito',10),
('eletronica-sensores-redes','módulo eletrônico',9),
('eletronica-sensores-redes','central eletrônica',9),
('eletronica-sensores-redes','rede can',10),
('eletronica-sensores-redes','falha de comunicação',9),
('eletronica-sensores-redes','código de falha',8),
('eletronica-sensores-redes','atuador',7),
('eletronica-sensores-redes','ecu',8),
('eletronica-sensores-redes','avaria eletrônica',9),

('painel-cluster-comandos','cluster',10),
('painel-cluster-comandos','painel de instrumentos',10),
('painel-cluster-comandos','computador de bordo',9),
('painel-cluster-comandos','mensagem no painel',9),
('painel-cluster-comandos','luz no painel',9),
('painel-cluster-comandos','botão no painel',9),
('painel-cluster-comandos','botões do volante',9),
('painel-cluster-comandos','indicador de combustível',8),
('painel-cluster-comandos','velocímetro',9),
('painel-cluster-comandos','conta giros',8),
('painel-cluster-comandos','display apagado',9),

('iluminacao-sinalizacao','farol',8),
('iluminacao-sinalizacao','farol alto',9),
('iluminacao-sinalizacao','farol baixo',9),
('iluminacao-sinalizacao','lanterna traseira',9),
('iluminacao-sinalizacao','luz de freio',10),
('iluminacao-sinalizacao','luz de ré',9),
('iluminacao-sinalizacao','seta não funciona',10),
('iluminacao-sinalizacao','pisca alerta',9),
('iluminacao-sinalizacao','iluminação interna',8),
('iluminacao-sinalizacao','lâmpada queimada',9),

('visibilidade-limpeza-vidros','limpador de para-brisa',10),
('visibilidade-limpeza-vidros','limpador do para-brisa',10),
('visibilidade-limpeza-vidros','limpador de parabrisa',10),
('visibilidade-limpeza-vidros','limpador do parabrisa',10),
('visibilidade-limpeza-vidros','limpador',8),
('visibilidade-limpeza-vidros','palheta',9),
('visibilidade-limpeza-vidros','esguicho do limpador',10),
('visibilidade-limpeza-vidros','lavador do para-brisa',10),
('visibilidade-limpeza-vidros','reservatório do limpador',9),
('visibilidade-limpeza-vidros','para-brisa',8),
('visibilidade-limpeza-vidros','parabrisa',8),
('visibilidade-limpeza-vidros','vidro embaçado',9),
('visibilidade-limpeza-vidros','desembaçador',9),
('visibilidade-limpeza-vidros','retrovisor',8),
('visibilidade-limpeza-vidros','espelho externo',8),

('climatizacao-ventilacao','ar-condicionado',10),
('climatizacao-ventilacao','ar condicionado',10),
('climatizacao-ventilacao','não está gelando',9),
('climatizacao-ventilacao','não gela',9),
('climatizacao-ventilacao','ventilação da cabine',9),
('climatizacao-ventilacao','ventilador interno',9),
('climatizacao-ventilacao','compressor do ar',9),
('climatizacao-ventilacao','saída de ar',8),
('climatizacao-ventilacao','aquecedor da cabine',9),
('climatizacao-ventilacao','climatizador',9),

('cabine-ergonomia-conforto','assoalho quente',10),
('cabine-ergonomia-conforto','calor nas pernas',10),
('cabine-ergonomia-conforto','cabine quente',9),
('cabine-ergonomia-conforto','isolamento térmico',9),
('cabine-ergonomia-conforto','banco do motorista',9),
('cabine-ergonomia-conforto','posição de dirigir',8),
('cabine-ergonomia-conforto','desconforto',7),
('cabine-ergonomia-conforto','ruído na cabine',9),
('cabine-ergonomia-conforto','vibração na cabine',9),
('cabine-ergonomia-conforto','cabine balançando',8),
('cabine-ergonomia-conforto','cinto de segurança',8),

('carroceria-portas-acabamento','porta não fecha',10),
('carroceria-portas-acabamento','porta não abre',10),
('carroceria-portas-acabamento','fechadura',8),
('carroceria-portas-acabamento','maçaneta',8),
('carroceria-portas-acabamento','infiltração de água',10),
('carroceria-portas-acabamento','acabamento soltando',9),
('carroceria-portas-acabamento','revestimento interno',8),
('carroceria-portas-acabamento','tampa lateral',8),
('carroceria-portas-acabamento','para-choque',8),
('carroceria-portas-acabamento','carroceria trincada',10),

('seguranca-ativa-adas','acc',9),
('seguranca-ativa-adas','controle de cruzeiro adaptativo',10),
('seguranca-ativa-adas','alerta de faixa',10),
('seguranca-ativa-adas','saída de faixa',9),
('seguranca-ativa-adas','frenagem autônoma',10),
('seguranca-ativa-adas','radar frontal',10),
('seguranca-ativa-adas','câmera frontal',9),
('seguranca-ativa-adas','assistente de condução',9),
('seguranca-ativa-adas','sensor de ponto cego',10),
('seguranca-ativa-adas','controle de estabilidade',9),

('tracao-eletrica-bateria-recarga','bateria de alta tensão',10),
('tracao-eletrica-bateria-recarga','motor elétrico',10),
('tracao-eletrica-bateria-recarga','tração elétrica',10),
('tracao-eletrica-bateria-recarga','inversor',9),
('tracao-eletrica-bateria-recarga','não carrega',9),
('tracao-eletrica-bateria-recarga','carregamento rápido',8),
('tracao-eletrica-bateria-recarga','conector de recarga',9),
('tracao-eletrica-bateria-recarga','baixa autonomia',10),
('tracao-eletrica-bateria-recarga','frenagem regenerativa',9),
('tracao-eletrica-bateria-recarga','isolamento de alta tensão',10),

('acessibilidade-passageiros','elevador para cadeirante',10),
('acessibilidade-passageiros','rampa de acessibilidade',10),
('acessibilidade-passageiros','ajoelhamento do ônibus',10),
('acessibilidade-passageiros','catraca',9),
('acessibilidade-passageiros','campainha',8),
('acessibilidade-passageiros','solicitação de parada',9),
('acessibilidade-passageiros','porta do ônibus',9),
('acessibilidade-passageiros','porta pneumática',9),
('acessibilidade-passageiros','itinerário eletrônico',8),
('acessibilidade-passageiros','sistema de passageiros',8),

('conectividade-telematica','telemetria',10),
('conectividade-telematica','rastreamento',9),
('conectividade-telematica','gps',8),
('conectividade-telematica','multimídia',8),
('conectividade-telematica','bluetooth',8),
('conectividade-telematica','sem conexão',8),
('conectividade-telematica','aplicativo do veículo',9),
('conectividade-telematica','dados da frota',8),
('conectividade-telematica','conectividade',9),
('conectividade-telematica','comunicação remota',9),

('nvh-ruidos-vibracoes','nvh',10),
('nvh-ruidos-vibracoes','vibração',9),
('nvh-ruidos-vibracoes','trepidação',9),
('nvh-ruidos-vibracoes','ruído estrutural',9),
('nvh-ruidos-vibracoes','ressonância',9),
('nvh-ruidos-vibracoes','aspereza',7),
('nvh-ruidos-vibracoes','vibra em velocidade',9),

('ruidos-externos-aerodinamica','ruído de vento',10),
('ruidos-externos-aerodinamica','barulho de vento',10),
('ruidos-externos-aerodinamica','ruído aerodinâmico',10),
('ruidos-externos-aerodinamica','assobio externo',9),
('ruidos-externos-aerodinamica','barulho dos pneus',9),
('ruidos-externos-aerodinamica','ruído da carga',9),
('ruidos-externos-aerodinamica','vedação externa',8),

('sugestao-produto','sugestão de melhoria',10),
('sugestao-produto','sugestão',8),
('sugestao-produto','poderia ter',9),
('sugestao-produto','gostaria que tivesse',10),
('sugestao-produto','melhoria no produto',9),
('sugestao-produto','nova função',9);

INSERT INTO category_terms (categoria_id,termo,peso,ativo)
SELECT mc.id,seed.termo,seed.peso,1
  FROM dl_category_terms_seed seed
  JOIN master_categories mc ON mc.slug=seed.categoria_slug
ON DUPLICATE KEY UPDATE
    peso=VALUES(peso),
    ativo=1;

DROP TEMPORARY TABLE IF EXISTS dl_category_terms_seed;

INSERT IGNORE INTO schema_migrations (versao)
VALUES ('20260729_020_category_terms_automotivos');
