<?php $settings=$assistantSettings??[]; ?>
<section class="page-heading split"><div><span class="eyebrow blue">Política de utilização</span><h1>Limites do assistente</h1><p>Defina a franquia diária padrão e exceções específicas por empresa. Passos locais do Service Desk não consomem a franquia.</p></div><span class="ai-master-badge"><i class="bi bi-shield-lock"></i> Administrador Master</span></section>
<?php if($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<?php if(!($settings['ready']??false)): ?><section class="empty-state"><h2>Atualização de banco pendente</h2><p>Execute a migração 018 na HostGator.</p></section><?php else: ?>
<section class="limit-overview"><article><i class="bi bi-globe2"></i><div><small>Limite global atual</small><strong><?= (int)$settings['global'] ?> consultas/dia</strong><span>Aplicado quando não houver exceção.</span></div></article><article><i class="bi bi-buildings"></i><div><small>Empresas com exceção</small><strong><?= count($settings['overrides']) ?></strong><span>Preparado para diferenciação por plano.</span></div></article><article><i class="bi bi-headset"></i><div><small>Relatos ao Service Desk</small><strong>Não bloqueados</strong><span>Continuam disponíveis após a franquia.</span></div></article></section>
<section class="settings-grid"><form class="panel settings-form" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_global"><span class="eyebrow blue">Política padrão</span><h2>Limite global</h2><label>Consultas por usuário/dia<input type="number" name="limite_diario" min="1" max="1000" value="<?= (int)$settings['global'] ?>" required></label><label>Observação<textarea name="observacao" rows="3" maxlength="500"><?= e($settings['global_row']['observacao']??'') ?></textarea></label><button class="btn primary">Salvar política global</button></form>
<form class="panel settings-form" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_company"><span class="eyebrow blue">Exceção por empresa</span><h2>Limite específico</h2><label>Empresa<select name="empresa_id" required><option value="">Selecione</option><?php foreach($settings['companies'] as $company): ?><option value="<?= (int)$company['id'] ?>"><?= e($company['nome_fantasia'].' · '.$company['tipo']) ?></option><?php endforeach; ?></select></label><label>Consultas por usuário/dia<input type="number" name="limite_diario" min="1" max="1000" value="<?= (int)$settings['global'] ?>" required></label><label>Observação<textarea name="observacao" rows="3" maxlength="500" placeholder="Ex.: condição comercial temporária"></textarea></label><button class="btn primary">Adicionar exceção</button></form></section>
<section class="panel"><div class="panel-head"><div><h2>Exceções configuradas</h2><p>Empresas não listadas utilizam <?= (int)$settings['global'] ?> consultas por usuário/dia.</p></div></div><div class="table-wrap"><table><thead><tr><th>Empresa</th><th>Tipo</th><th>Limite diário</th><th>Observação</th><th>Ações</th></tr></thead><tbody><?php if(!$settings['overrides']): ?><tr><td colspan="5"><div class="table-empty"><i class="bi bi-check2-circle"></i><strong>Nenhuma exceção cadastrada</strong></div></td></tr><?php endif; ?><?php foreach($settings['overrides'] as $row): ?><tr><td><strong><?= e($row['nome_fantasia']) ?></strong></td><td><?= e(ucfirst($row['tipo'])) ?></td><td><form class="inline-limit-form" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_company"><input type="hidden" name="empresa_id" value="<?= (int)$row['empresa_id'] ?>"><input type="hidden" name="observacao" value="<?= e($row['observacao']) ?>"><input type="number" name="limite_diario" min="1" max="1000" value="<?= (int)$row['limite_diario'] ?>"><button class="action-btn" aria-label="Salvar novo limite"><i class="bi bi-check-lg"></i></button></form></td><td><?= e($row['observacao']?:'Sem observação') ?></td><td><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete_company"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="action-btn danger" aria-label="Remover exceção"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php endif; ?>
