<?php
$isClient=$companyMode==='cliente';$companies=$access['companies']??[];$q=$access['q']??'';$status=$access['status']??'';$page=$access['page']??1;$perPage=$access['perPage']??10;$offset=$access['offset']??0;$totalRows=$access['totalRows']??0;$totalPages=$access['totalPages']??1;
$routeName=$isClient?'clientes':'empresas-vwco';$resourceName=$isClient?'clients':'organizations';
?>
<section class="page-heading split"><div><span class="eyebrow blue">Administração e acessos</span><h1><?= $isClient?'Empresas clientes':'Empresas Volkswagen' ?></h1><p><?= $isClient?'Cadastre clientes e vincule cada um a uma ou mais concessionárias ou unidades VWCO.':'Organize fábricas, polos, concessionárias, assistências e suas filiais.' ?></p></div><?php if(can($resourceName,'create')): ?><button class="btn primary" data-company-create><i class="bi bi-plus-lg"></i> <?= $isClient?'Novo cliente':'Nova empresa' ?></button><?php endif; ?></section>
<?php if($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><i class="bi <?= $flash['type']==='success'?'bi-check-circle':'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>
<section class="panel">
<form class="panel-head table-filters" method="get" action="<?= url($routeName) ?>"><div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($q) ?>" placeholder="Buscar por empresa, documento ou cidade..."></div><div class="panel-filters"><select name="status"><option value="">Todas as situações</option><option value="ativo" <?= $status==='ativo'?'selected':'' ?>>Ativas</option><option value="inativo" <?= $status==='inativo'?'selected':'' ?>>Inativas</option></select><button class="btn secondary"><i class="bi bi-search"></i> Buscar</button><?php if($q!==''||$status!==''): ?><a class="btn secondary" href="<?= url($routeName) ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?></div></form>
<div class="table-wrap"><table><thead><tr><th>Empresa</th><th>Tipo e localização</th><th><?= $isClient?'Atendimento':'Estrutura' ?></th><th>Usuários</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
<?php if(!$companies): ?><tr><td colspan="6"><div class="table-empty"><i class="bi bi-buildings"></i><strong>Nenhuma empresa encontrada</strong><span>Cadastre a primeira empresa para iniciar os vínculos de acesso.</span></div></td></tr><?php endif; ?>
<?php foreach($companies as $company): $payload=['id'=>(int)$company['id'],'tipo'=>$company['tipo'],'subtipo'=>$company['subtipo'],'razao_social'=>$company['razao_social'],'nome_fantasia'=>$company['nome_fantasia'],'documento'=>$company['documento'],'email'=>$company['email'],'telefone'=>$company['telefone'],'estado_id'=>$company['estado_id'],'cidade'=>$company['cidade_nome'],'endereco'=>$company['endereco'],'cep'=>$company['cep'],'logo_url'=>$company['logo']?url($company['logo']):null,'empresa_pai_id'=>$company['empresa_pai_id'],'ativo'=>(int)$company['ativo'],'parceiros'=>array_values(array_filter(explode(',',(string)$company['parceiro_ids'])))] ?>
<tr><td><div class="entity-cell"><?php if($company['logo']): ?><img class="company-list-logo" src="<?= url($company['logo']) ?>" alt="Logotipo de <?= e($company['nome_fantasia']) ?>"><?php else: ?><span class="entity-placeholder"><i class="bi <?= $isClient?'bi-truck':'bi-building' ?>"></i></span><?php endif; ?><div><strong><?= e($company['nome_fantasia']) ?></strong><small><?= e($company['razao_social']) ?></small><small><?= e($company['documento']?:'Documento não informado') ?></small></div></div></td><td><span class="pill"><?= e($isClient?'Cliente':($company['tipo']==='vwco'?'VWCO':'Concessionária')) ?></span><small><?= e(trim(($company['cidade_nome']?:'Cidade não informada').' '.($company['uf']?'/ '.$company['uf']:''))) ?></small></td><td><strong><?= (int)$company['vinculos'] ?> <?= $isClient?'empresa(s) atendente(s)':'cliente(s)' ?></strong><small><?= $company['empresa_pai_nome']?'Unidade de '.e($company['empresa_pai_nome']):'Cadastro independente' ?></small></td><td><?= (int)$company['usuarios'] ?> usuário(s)</td><td><span class="status <?= $company['ativo']?'active':'inactive' ?>"><?= $company['ativo']?'Ativa':'Inativa' ?></span></td><td><div class="row-actions"><?php if(can($resourceName,'update')): ?><button class="action-btn" data-company-edit data-company="<?= e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>" aria-label="Editar <?= e($company['nome_fantasia']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if(can($resourceName,'delete')&&$company['ativo']): ?><button class="action-btn danger" data-company-delete data-id="<?= (int)$company['id'] ?>" data-name="<?= e($company['nome_fantasia']) ?>" aria-label="Desativar <?= e($company['nome_fantasia']) ?>"><i class="bi bi-archive"></i></button><?php endif; ?></div></td></tr>
<?php endforeach; ?></tbody></table></div>
<div class="pagination"><form method="get" action="<?= url($routeName) ?>" class="per-page"><input type="hidden" name="q" value="<?= e($q) ?>"><input type="hidden" name="status" value="<?= e($status) ?>"><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows?$offset+1:0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons" aria-label="Paginação"><?php if($page>1): ?><a href="<?= page_url($routeName,['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url($routeName,['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url($routeName,['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div>
</section>

<div class="modal" id="company-modal" aria-hidden="true"><div class="modal-dialog access-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Organização e acesso</span><h2 data-company-modal-title><?= $isClient?'Novo cliente':'Nova empresa' ?></h2><p>Os dados desta empresa serão usados nos vínculos de usuários, clientes, frotas e relatórios.</p><form method="post" enctype="multipart/form-data" data-company-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id"><div class="form-grid">
<label class="full image-upload company-image-upload"><span class="image-preview company-logo-preview" data-company-logo-preview><i class="bi bi-building"></i></span><span><strong><?= $isClient?'Logotipo do cliente':'Logotipo da empresa' ?> (opcional)</strong><small>JPG, PNG ou WEBP, com até 3 MB.</small><input type="file" name="logo" accept="image/jpeg,image/png,image/webp" data-company-logo></span></label>
<?php if(!$isClient): ?><label>Tipo de empresa<select name="tipo" required><option value="vwco">Unidade VWCO</option><option value="concessionaria">Concessionária</option></select></label><?php endif; ?><label>Classificação<select name="subtipo"><option value="matriz">Matriz</option><option value="filial">Filial</option><?php if(!$isClient): ?><option value="fabrica">Fábrica</option><option value="polo">Polo VWCO</option><option value="assistencia">Assistência técnica</option><?php endif; ?><option value="outro">Outro</option></select></label>
<label class="full">Razão social<input name="razao_social" maxlength="180" required></label><label class="full">Nome fantasia<input name="nome_fantasia" maxlength="180" required></label><label>CPF ou CNPJ<input name="documento" inputmode="numeric" maxlength="20"></label><label>Telefone<input name="telefone" maxlength="30"></label><label class="full">E-mail corporativo<input type="email" name="email" maxlength="180"></label>
<label>Estado<select name="estado_id"><option value="">Selecione</option><?php foreach($access['states']??[] as $state): ?><option value="<?= (int)$state['id'] ?>"><?= e($state['nome'].' — '.$state['sigla']) ?></option><?php endforeach; ?></select></label><label>Cidade<input name="cidade" maxlength="120" placeholder="Ex.: Resende"></label><label>CEP<input name="cep" maxlength="10"></label><label class="full">Endereço<input name="endereco" maxlength="220"></label>
<?php if(!$isClient): ?><label class="full">Empresa principal<select name="empresa_pai_id"><option value="">Cadastro independente</option><?php foreach($access['parentOptions']??[] as $parent): ?><option value="<?= (int)$parent['id'] ?>"><?= e($parent['nome_fantasia']) ?></option><?php endforeach; ?></select></label><?php endif; ?>
<?php if($isClient): ?><fieldset class="full link-fieldset"><legend>Empresas que atendem este cliente</legend><p>Um cliente pode ser vinculado a várias concessionárias, fábricas ou polos.</p><div class="selection-search search"><span><i class="bi bi-search"></i></span><input type="search" placeholder="Buscar empresa VWCO ou concessionária..." data-partner-selection-search></div><div class="selection-grid partner-selection" data-partner-selection><?php foreach($access['partnerOptions']??[] as $partner): ?><label data-partner-label><input type="checkbox" name="empresas_vw[]" value="<?= (int)$partner['id'] ?>"><span><i class="bi bi-building-check"></i><strong><?= e($partner['nome_fantasia']) ?></strong><small><?= $partner['tipo']==='vwco'?'VWCO':'Concessionária' ?></small></span></label><?php endforeach; ?></div></fieldset><?php endif; ?>
<label class="full check"><input type="checkbox" name="ativo" checked> Empresa ativa</label></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar <?= $isClient?'cliente':'empresa' ?></button></div></form></div></div></div>
<div class="modal" id="delete-company-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-archive"></i></span><h2>Desativar empresa?</h2><p>O acesso de <strong data-delete-company-name></strong> será bloqueado, mas vínculos e históricos permanecerão preservados.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-company-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger"><i class="bi bi-archive"></i> Desativar</button></div></form></div></div></div>
