<section class="page-heading split">
    <div><span class="eyebrow blue">Gestão de conteúdo</span><h1>Famílias de veículos</h1><p>Organize as linhas Volkswagen que agrupam os modelos e treinamentos.</p></div>
    <?php if (can('families','create')): ?><button class="btn primary" data-family-create><i class="bi bi-plus-lg"></i> Nova família</button><?php endif; ?>
</section>

<?php if ($flash): ?><div class="alert <?= $flash['type'] === 'success' ? 'success' : 'error' ?>"><i class="bi <?= $flash['type'] === 'success' ? 'bi-check-circle' : 'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>

<section class="panel">
    <form class="panel-head table-filters" method="get" action="<?= url('familias') ?>"><div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($q) ?>" placeholder="Buscar família..."></div><div class="panel-filters"><select name="status"><option value="">Todas as situações</option><option value="ativo" <?= $status==='ativo'?'selected':'' ?>>Ativas</option><option value="inativo" <?= $status==='inativo'?'selected':'' ?>>Inativas</option></select><button class="btn secondary"><i class="bi bi-search"></i> Buscar</button><?php if ($q!==''||$status!==''): ?><a class="btn secondary" href="<?= url('familias') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?></div></form>
    <div class="table-wrap"><table><thead><tr><th>Família</th><th>Descrição</th><th>Modelos</th><th>Vídeos</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
    <?php if (!$families): ?><tr><td colspan="6"><div class="table-empty"><i class="bi bi-collection"></i><strong>Nenhuma família cadastrada</strong><span>Cadastre a primeira família de veículos.</span></div></td></tr><?php endif; ?>
    <?php foreach($families as $family): ?><tr data-search-row data-status="<?= $family['ativo'] ? 'ativo' : 'inativo' ?>">
        <td><div class="entity-cell"><?php if ($family['imagem']): ?><img src="<?= url($family['imagem']) ?>" alt="Imagem da família <?= e($family['nome']) ?>"><?php else: ?><span class="entity-placeholder"><i class="bi bi-truck-front"></i></span><?php endif; ?><div><strong><?= e($family['nome']) ?></strong><small>Cadastrada em <?= date('d/m/Y', strtotime($family['criado_em'])) ?></small></div></div></td>
        <td class="description-cell"><?= e($family['descricao'] ?: 'Sem descrição') ?></td><td><?= (int)$family['modelos'] ?></td><td><?= (int)$family['videos'] ?></td>
        <td><span class="status <?= $family['ativo'] ? 'active' : 'inactive' ?>"><?= $family['ativo'] ? 'Ativa' : 'Inativa' ?></span></td>
        <td><div class="row-actions"><?php if (can('families','update')): ?><button class="action-btn" data-family-edit data-id="<?= (int)$family['id'] ?>" data-name="<?= e($family['nome']) ?>" data-description="<?= e($family['descricao']) ?>" data-active="<?= (int)$family['ativo'] ?>" data-image="<?= $family['imagem'] ? e(url($family['imagem'])) : '' ?>" aria-label="Editar <?= e($family['nome']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if (can('families','delete')): ?><button class="action-btn danger" data-family-delete data-id="<?= (int)$family['id'] ?>" data-name="<?= e($family['nome']) ?>" aria-label="Excluir <?= e($family['nome']) ?>"><i class="bi bi-trash"></i></button><?php endif; ?></div></td>
    </tr><?php endforeach; ?></tbody></table></div>
    <div class="pagination"><form method="get" action="<?= url('familias') ?>" class="per-page"><input type="hidden" name="q" value="<?= e($q) ?>"><input type="hidden" name="status" value="<?= e($status) ?>"><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows ? $offset+1 : 0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons" aria-label="Paginação"><?php if($page>1): ?><a href="<?= page_url('familias',['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url('familias',['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url('familias',['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div>
</section>

<div class="modal" id="family-modal" aria-hidden="true"><div class="modal-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content">
    <span class="eyebrow blue">Cadastro de conteúdo</span><h2 data-family-modal-title>Nova família</h2><p>Preencha os dados da linha de veículos. A imagem será usada nos cards da plataforma.</p>
    <form method="post" enctype="multipart/form-data" data-family-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id">
        <div class="form-grid"><label>Nome da família<input name="nome" maxlength="100" required placeholder="Ex.: Constellation"></label><label class="full">Descrição<textarea name="descricao" rows="4" maxlength="2000" placeholder="Descreva os principais diferenciais da família"></textarea></label><label class="full image-upload"><span class="image-preview" data-image-preview><i class="bi bi-image"></i></span><span><strong>Imagem da família</strong><small>JPG, PNG ou WEBP de até 5 MB</small><input type="file" name="imagem" accept="image/jpeg,image/png,image/webp" data-image-input></span></label><label class="check full"><input type="checkbox" name="ativo" checked> Família ativa e visível na plataforma</label></div>
        <div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary" type="submit"><i class="bi bi-check-lg"></i> Salvar família</button></div>
    </form>
</div></div></div>

<div class="modal" id="delete-family-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-trash"></i></span><h2>Excluir família?</h2><p>Você está prestes a excluir <strong data-delete-family-name></strong>. Esta ação não poderá ser desfeita.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-family-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger" type="submit"><i class="bi bi-trash"></i> Excluir família</button></div></form></div></div></div>
