<?php
$rows=$fleet['rows']??[];$clients=$fleet['clients']??[];$families=$fleet['families']??[];$models=$fleet['models']??[];$standards=$fleet['standards']??[];$metrics=$fleet['metrics']??['vehicles'=>0,'families'=>0,'videos'=>0];
$page=$fleet['page']??1;$perPage=$fleet['perPage']??10;$offset=$fleet['offset']??0;$totalRows=$fleet['totalRows']??0;$totalPages=$fleet['totalPages']??1;$q=$fleet['q']??'';$familyFilter=$fleet['familyFilter']??0;$standardFilter=$fleet['standardFilter']??0;$clientFilter=$fleet['clientFilter']??0;$isClient=(user()['active_company_type']??'')==='cliente';
?>
<section class="page-heading split"><div><span class="eyebrow blue">Gestão de veículos</span><h1><?= $isClient?'Minha frota':'Frotas dos clientes' ?></h1><p><?= $isClient?'Cadastre os veículos Volkswagen da sua empresa para receber treinamentos compatíveis.':'Consulte e mantenha as frotas dos clientes disponíveis no seu escopo de atendimento.' ?></p></div><?php if(can('fleet','create')&&($clients||$isClient)): ?><button class="btn primary" data-fleet-create><i class="bi bi-plus-lg"></i> Adicionar composição</button><?php endif; ?></section>
<?php if($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><i class="bi <?= $flash['type']==='success'?'bi-check-circle':'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>
<section class="metrics mini"><article class="metric"><span class="metric-icon blue"><i class="bi bi-truck"></i></span><div><small>Total de veículos</small><strong><?= number_format((int)$metrics['vehicles'],0,',','.') ?></strong></div></article><article class="metric"><span class="metric-icon green"><i class="bi bi-collection"></i></span><div><small>Famílias na frota</small><strong><?= (int)$metrics['families'] ?></strong></div></article><article class="metric"><span class="metric-icon orange"><i class="bi bi-play-circle"></i></span><div><small>Vídeos compatíveis</small><strong><?= (int)$metrics['videos'] ?></strong></div></article></section>
<section class="panel">
<form class="panel-head table-filters fleet-filters" method="get" action="<?= url('frota') ?>"><div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($q) ?>" placeholder="Buscar modelo, família, cliente ou norma..."></div><div class="panel-filters"><?php if(!$isClient&&count($clients)>1): ?><select name="cliente"><option value="">Todos os clientes</option><?php foreach($clients as $client): ?><option value="<?= (int)$client['id'] ?>" <?= $clientFilter===(int)$client['id']?'selected':'' ?>><?= e($client['nome_fantasia']) ?></option><?php endforeach; ?></select><?php endif; ?><select name="familia"><option value="">Todas as famílias</option><?php foreach($families as $family): ?><option value="<?= (int)$family['id'] ?>" <?= $familyFilter===(int)$family['id']?'selected':'' ?>><?= e($family['nome']) ?></option><?php endforeach; ?></select><select name="norma"><option value="">Todas as normas</option><?php foreach($standards as $standard): ?><option value="<?= (int)$standard['id'] ?>" <?= $standardFilter===(int)$standard['id']?'selected':'' ?>><?= e($standard['nome']) ?></option><?php endforeach; ?></select><button class="btn secondary"><i class="bi bi-search"></i> Buscar</button><?php if($q!==''||$familyFilter||$standardFilter||(!$isClient&&$clientFilter)): ?><a class="btn secondary" href="<?= url('frota') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?></div></form>
<div class="table-wrap"><table><thead><tr><th>Veículo</th><?php if(!$isClient): ?><th>Cliente</th><?php endif; ?><th>Ano e emissões</th><th>Quantidade</th><th>Conteúdos</th><th>Observação</th><th>Ações</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="<?= $isClient?6:7 ?>"><div class="table-empty"><i class="bi bi-truck"></i><strong>Nenhuma composição encontrada</strong><span><?= ($clients||$isClient)?'Cadastre o primeiro grupo de veículos desta frota.':'Vincule um cliente à empresa ativa para visualizar sua frota.' ?></span></div></td></tr><?php endif; ?>
<?php foreach($rows as $row): $payload=['id'=>(int)$row['id'],'cliente_empresa_id'=>(int)$row['cliente_empresa_id'],'familia_id'=>(int)$row['familia_id'],'modelo_id'=>(int)$row['modelo_id'],'quantidade'=>(int)$row['quantidade'],'ano'=>(int)$row['ano'],'norma_emissao_id'=>(int)$row['norma_emissao_id'],'observacao'=>$row['observacao']]; ?>
<tr><td><div class="entity-cell"><?php if($row['modelo_imagem']): ?><img src="<?= url($row['modelo_imagem']) ?>" alt="<?= e($row['modelo_nome']) ?>"><?php else: ?><span class="entity-placeholder"><i class="bi bi-truck-front"></i></span><?php endif; ?><div><strong><?= e($row['modelo_nome']) ?></strong><small><?= e($row['familia_nome']) ?></small></div></div></td><?php if(!$isClient): ?><td><strong><?= e($row['cliente_nome']) ?></strong><small>Empresa cliente</small></td><?php endif; ?><td><span class="emission-badge"><i class="bi bi-cloud-haze2"></i> <?= e($row['norma_nome']?:'Não informada') ?></span><small>Ano <?= (int)$row['ano'] ?></small></td><td><strong><?= number_format((int)$row['quantidade'],0,',','.') ?></strong><small>veículo(s)</small></td><td><strong><?= (int)$row['videos'] ?> vídeo(s)</strong><small>Família e modelo</small></td><td class="description-cell"><?= e($row['observacao']?:'Sem observação') ?></td><td><div class="row-actions"><?php if(can('fleet','update')): ?><button class="action-btn" data-fleet-edit data-fleet="<?= e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>" aria-label="Editar <?= e($row['modelo_nome']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if(can('fleet','delete')): ?><button class="action-btn danger" data-fleet-delete data-id="<?= (int)$row['id'] ?>" data-name="<?= e($row['modelo_nome'].' · '.$row['ano'].' · '.($row['norma_nome']?:'Sem norma')) ?>" aria-label="Excluir composição"><i class="bi bi-trash"></i></button><?php endif; ?></div></td></tr>
<?php endforeach; ?></tbody></table></div>
<div class="pagination"><form method="get" action="<?= url('frota') ?>" class="per-page"><input type="hidden" name="q" value="<?= e($q) ?>"><input type="hidden" name="cliente" value="<?= (int)$clientFilter ?>"><input type="hidden" name="familia" value="<?= (int)$familyFilter ?>"><input type="hidden" name="norma" value="<?= (int)$standardFilter ?>"><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows?$offset+1:0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons" aria-label="Paginação"><?php if($page>1): ?><a href="<?= page_url('frota',['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url('frota',['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url('frota',['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div>
</section>

<div class="modal" id="fleet-modal" aria-hidden="true"><div class="modal-dialog access-dialog fleet-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Composição da frota</span><h2 data-fleet-modal-title>Adicionar veículos</h2><p>Cadastre veículos agrupados por modelo, ano e norma de emissões.</p><form method="post" data-fleet-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id"><div class="form-grid">
<?php if(!$isClient): ?><label class="full">Empresa cliente<select name="cliente_empresa_id" required><option value="">Selecione o cliente</option><?php foreach($clients as $client): ?><option value="<?= (int)$client['id'] ?>"><?= e($client['nome_fantasia']) ?></option><?php endforeach; ?></select></label><?php endif; ?>
<label>Família<select name="familia_id" data-fleet-family required><option value="">Selecione a família</option><?php foreach($families as $family): ?><option value="<?= (int)$family['id'] ?>"><?= e($family['nome']) ?></option><?php endforeach; ?></select></label><label>Modelo<select name="modelo_id" data-fleet-model required><option value="">Selecione o modelo</option><?php foreach($models as $model): ?><option value="<?= (int)$model['id'] ?>" data-family="<?= (int)$model['familia_id'] ?>"><?= e($model['nome']) ?></option><?php endforeach; ?></select></label><label>Quantidade de veículos<input type="number" name="quantidade" min="1" max="100000" value="1" required></label><label>Ano da frota<input type="number" name="ano" min="1950" max="<?= (int)date('Y')+2 ?>" value="<?= (int)date('Y') ?>" required></label><label class="full">Norma de emissões<select name="norma_emissao_id" required><option value="">Selecione a norma</option><?php foreach($standards as $standard): ?><option value="<?= (int)$standard['id'] ?>"><?= e($standard['nome']) ?> — <?= e($standard['codigo']) ?></option><?php endforeach; ?></select><small>Novas normas podem ser incluídas pelo administrador sem alterar este cadastro.</small></label><label class="full">Observação<textarea name="observacao" rows="3" maxlength="1000" placeholder="Ex.: veículos da operação urbana da filial de São Paulo"></textarea></label></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar composição</button></div></form></div></div></div>
<div class="modal" id="delete-fleet-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-trash"></i></span><h2>Excluir composição?</h2><p>O grupo <strong data-delete-fleet-name></strong> será removido da frota.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-fleet-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger"><i class="bi bi-trash"></i> Excluir</button></div></form></div></div></div>
