<?php
$definitions = [
'families'=>['Famílias de veículos','Organize as linhas Volkswagen que agrupam os modelos.','Nova família',['Família','Descrição','Modelos','Vídeos','Situação']],
'models'=>['Modelos','Cadastre imagens e especificações técnicas de cada veículo.','Novo modelo',['Modelo','Família','Potência','PBT','Vídeos','Situação']],
'categories'=>['Categorias e subcategorias','Estruture os treinamentos pelas funções do veículo.','Nova categoria',['Categoria','Subcategorias','Vídeos','Última atualização','Situação']],
'videos'=>['Vídeos','Publique instruções e vincule-as a famílias, modelos e categorias.','Novo vídeo',['Título','Categoria','Vinculação','Duração','Visualizações','Situação']],
'clients'=>['Clientes','Gerencie empresas, unidades e acessos às frotas.','Novo cliente',['Cliente','Documento','Unidade','Usuários','Veículos','Situação']],
'users'=>['Usuários','Controle as pessoas que acessam a plataforma.','Novo usuário',['Nome','E-mail','Perfil','Organização','Último acesso','Situação']],
'permissions'=>['Perfis e permissões','Defina o que cada perfil pode visualizar, inserir, editar e excluir.','Novo perfil',['Perfil','Escopo','Visualizar','Inserir','Editar','Excluir']],
'reports'=>['Relatórios e avaliações','Meça o alcance, as conclusões, as avaliações e as oportunidades de melhoria.','Exportar relatório',['Indicador','Período','Resultado','Evolução','Detalhes']],
];
$d=$definitions[$resource]??['Módulo','Conteúdo em preparação.','Novo item',['Item','Situação']];
?>
<section class="page-heading split"><div><span class="eyebrow blue">Administração</span><h1><?= e($d[0]) ?></h1><p><?= e($d[1]) ?></p></div><button class="btn primary" data-open-form><i class="bi bi-plus-lg"></i> <?= e($d[2]) ?></button></section>
<section class="panel">
    <div class="panel-head"><div class="search"><span><i class="bi bi-search"></i></span><input type="search" placeholder="Buscar nesta página..." data-table-search></div><div class="panel-filters"><select><option>Todas as situações</option><option>Ativo</option><option>Inativo</option></select><button class="btn secondary"><i class="bi bi-sliders"></i> Mais filtros</button></div></div>
    <div class="table-wrap"><table><thead><tr><?php foreach($d[3] as $head): ?><th><?= e($head) ?></th><?php endforeach; ?><th>Ações</th></tr></thead><tbody><?php for($i=1;$i<=5;$i++): ?><tr data-search-row><?php foreach($d[3] as $j=>$head): ?><td><?php if($j===0): ?><strong><?= e($d[0]) ?> <?= $i ?></strong><small>Registro de demonstração</small><?php elseif($head==='Situação'): ?><span class="status active">Ativo</span><?php elseif(in_array($head,['Visualizar','Inserir','Editar','Excluir'])): ?><label class="switch"><input type="checkbox" <?= $i<5?'checked':'' ?>><span></span></label><?php else: ?><?= 2*$i ?> registros<?php endif; ?></td><?php endforeach; ?><td><button class="more" aria-label="Abrir ações"><i class="bi bi-three-dots"></i></button></td></tr><?php endfor; ?></tbody></table></div>
    <div class="pagination"><span>Mostrando 1–5 de 5</span><div><button disabled aria-label="Página anterior"><i class="bi bi-arrow-left"></i></button><button class="active">1</button><button disabled aria-label="Próxima página"><i class="bi bi-arrow-right"></i></button></div></div>
</section>
<div class="modal" id="form-modal" aria-hidden="true"><div class="modal-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Cadastro</span><h2><?= e($d[2]) ?></h2><p>Preencha as informações principais. Os campos específicos serão exibidos conforme o tipo de cadastro.</p><form data-demo-form><div class="form-grid"><label>Nome ou título<input required placeholder="Digite o nome"></label><label>Situação<select><option>Ativo</option><option>Inativo</option><option>Rascunho</option></select></label><label class="full">Descrição<textarea rows="4" placeholder="Inclua uma descrição clara"></textarea></label><label class="full upload">Imagem ou anexo<input type="file"><span><i class="bi bi-cloud-arrow-up"></i> Arraste um arquivo ou clique para selecionar</span></label></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar cadastro</button></div></form></div></div></div>
