<?php
$videos=$library['videos']??[];$categories=$library['categories']??[];$brands=$library['brands']??[];$families=$library['families']??[];$models=$library['models']??[];$featured=$library['featured']??null;$grouped=$library['grouped']??[];$q=$library['q']??'';$categoryId=$library['categoryId']??0;$brandId=$library['brandId']??0;$familyId=$library['familyId']??0;$modelId=$library['modelId']??0;
$videoPayload=function(array $video):array{return ['id'=>(int)$video['id'],'titulo'=>$video['titulo'],'descricao'=>$video['descricao'],'tipo'=>$video['tipo'],'url'=>$video['play_url'],'youtube_id'=>$video['youtube_id'],'categoria_id'=>(int)$video['categoria_id'],'categoria'=>$video['categoria_nome'],'subcategoria'=>$video['subcategoria_nome'],'thumbnail'=>$video['thumbnail'],'duracao'=>(int)($video['duracao_segundos']??0),'progresso'=>(float)($video['progresso']??0),'concluido'=>(bool)($video['concluido']??false),'familias'=>array_values(array_filter(explode(',',(string)($video['familia_ids']??'')))),'modelos'=>array_values(array_filter(explode(',',(string)($video['modelo_ids']??''))))];};
$duration=function(?int $seconds):string{if(!$seconds)return 'Duração livre';return sprintf('%02d:%02d',intdiv($seconds,60),$seconds%60);};
?>
<section class="learning-page">
<?php if($featured): $featuredPayload=$videoPayload($featured); ?>
<article class="learning-hero" style="--hero-image:url('<?= e($featured['thumbnail']?:'') ?>')"><div class="learning-hero-content"><span class="hero-kicker"><i class="bi bi-stars"></i> Em destaque</span><span class="hero-category"><?= e($featured['categoria_nome']) ?><?= $featured['subcategoria_nome']?' · '.e($featured['subcategoria_nome']):'' ?></span><h1><?= e($featured['titulo']) ?></h1><p><?= e($featured['descricao']?:'Treinamento selecionado para apoiar a operação e o conhecimento da sua frota Volkswagen.') ?></p><div class="hero-actions"><button class="btn hero-play" data-library-play data-video="<?= e(json_encode($featuredPayload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>"><i class="bi bi-play-fill"></i> Assistir agora</button><span><i class="bi bi-clock"></i> <?= $duration($featured['duracao_segundos']?(int)$featured['duracao_segundos']:null) ?></span><?php if($featured['nota_media']): ?><span><i class="bi bi-star-fill"></i> <?= e((string)$featured['nota_media']) ?></span><?php endif; ?></div></div></article>
<?php else: ?><article class="learning-hero empty"><div class="learning-hero-content"><span class="hero-kicker"><i class="bi bi-play-circle"></i> Biblioteca de treinamentos</span><h1>Conteúdo sob medida para sua frota</h1><p>Nenhum vídeo publicado corresponde aos filtros ou aos veículos cadastrados.</p><?php if((user()['active_company_type']??'')==='cliente'): ?><a class="btn hero-play" href="<?= url('frota') ?>"><i class="bi bi-truck"></i> Conferir minha frota</a><?php endif; ?></div></article><?php endif; ?>

<form class="learning-filters" method="get" action="<?= url('biblioteca') ?>" data-brand-family-filters><div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($q) ?>" placeholder="Buscar treinamento, função ou assunto..."></div><select name="categoria"><option value="">Todas as categorias</option><?php foreach($categories as $category): ?><option value="<?= (int)$category['id'] ?>" <?= $categoryId===(int)$category['id']?'selected':'' ?>><?= e($category['nome']) ?></option><?php endforeach; ?></select><select name="marca" data-filter-brand><option value="">Todas as marcas</option><?php foreach($brands as $brand): ?><option value="<?= (int)$brand['id'] ?>" <?= $brandId===(int)$brand['id']?'selected':'' ?>><?= e($brand['nome']) ?></option><?php endforeach; ?></select><select name="familia" data-filter-family><option value="">Todas as famílias</option><?php foreach($families as $family): ?><option value="<?= (int)$family['id'] ?>" data-brand="<?= (int)$family['marca_id'] ?>" <?= $familyId===(int)$family['id']?'selected':'' ?>><?= e($family['marca_nome'].' · '.$family['nome']) ?></option><?php endforeach; ?></select><select name="modelo" data-filter-model><option value="">Todos os modelos</option><?php foreach($models as $model): ?><option value="<?= (int)$model['id'] ?>" data-brand="<?= (int)$model['marca_id'] ?>" data-family="<?= (int)$model['familia_id'] ?>" <?= $modelId===(int)$model['id']?'selected':'' ?>><?= e($model['marca_nome'].' · '.$model['nome']) ?></option><?php endforeach; ?></select><button class="btn primary"><i class="bi bi-sliders"></i> Filtrar</button><?php if($q!==''||$categoryId||$brandId||$familyId||$modelId): ?><a class="btn secondary" href="<?= url('biblioteca') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?></form>

<div class="category-strip" aria-label="Categorias de treinamento"><a class="category-pill <?= !$categoryId?'active':'' ?>" href="<?= page_url('biblioteca',['categoria'=>null]) ?>"><i class="bi bi-grid"></i><span>Todos<small><?= count($videos) ?> conteúdos</small></span></a><?php foreach($categories as $category): ?><a class="category-pill <?= $categoryId===(int)$category['id']?'active':'' ?>" href="<?= page_url('biblioteca',['categoria'=>$category['id']]) ?>"><i class="bi bi-<?= e($category['icone']?:'play-circle') ?>"></i><span><?= e($category['nome']) ?><small><?= (int)$category['videos'] ?> vídeos publicados</small></span></a><?php endforeach; ?></div>

<?php foreach($grouped as $categoryName=>$categoryVideos): ?><section class="training-row"><div class="training-row-title"><div><span>Categoria</span><h2><?= e($categoryName) ?></h2></div><small><?= count($categoryVideos) ?> treinamento(s)</small></div><div class="training-grid"><?php foreach($categoryVideos as $video): $payload=$videoPayload($video); ?><article class="training-card"><button class="training-cover" data-library-play data-video="<?= e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>" aria-label="Assistir <?= e($video['titulo']) ?>"><?php if($video['thumbnail']): ?><img src="<?= e($video['thumbnail']) ?>" alt="Capa de <?= e($video['titulo']) ?>" loading="lazy"><?php else: ?><span class="training-cover-fallback"><i class="bi bi-camera-video"></i></span><?php endif; ?><span class="training-play"><i class="bi bi-play-fill"></i></span><span class="training-duration"><?= $duration($video['duracao_segundos']?(int)$video['duracao_segundos']:null) ?></span><?php if($video['concluido']): ?><span class="training-complete"><i class="bi bi-check-lg"></i> Concluído</span><?php endif; ?><?php if((float)$video['progresso']>0&&!$video['concluido']): ?><span class="training-card-progress"><i style="width:<?= min(100,(float)$video['progresso']) ?>%"></i></span><?php endif; ?></button><div class="training-body"><span class="training-topic"><?= e($video['subcategoria_nome']?:$video['categoria_nome']) ?></span><h3><?= e($video['titulo']) ?></h3><p><?= e($video['modelos_nomes']?:($video['familias_nomes']?:'Conteúdo geral Volkswagen')) ?></p><div class="training-meta"><span><i class="bi bi-eye"></i> <?= (int)$video['visualizacoes'] ?></span><?php if($video['nota_media']): ?><span><i class="bi bi-star-fill"></i> <?= e((string)$video['nota_media']) ?></span><?php else: ?><span><i class="bi bi-star"></i> Sem avaliações</span><?php endif; ?></div></div></article><?php endforeach; ?></div></section><?php endforeach; ?>
</section>

<div class="modal training-modal" id="library-video-modal" aria-hidden="true"><div class="modal-dialog training-player-dialog"><button class="modal-close player-close" data-modal-close aria-label="Fechar vídeo"><i class="bi bi-x-lg"></i><span>Fechar</span></button><div class="training-player" data-library-player><div class="player-loading"><span></span><p>Preparando treinamento...</p></div></div><div class="training-detail"><div class="training-copy"><span class="tag" data-library-category>Treinamento</span><h2 data-library-title></h2><p data-library-description></p><div class="watch-status" data-watch-status><i class="bi bi-info-circle"></i><span>A visualização será registrada automaticamente.</span></div></div><form class="training-feedback" data-library-feedback hidden><?= csrf_field() ?><input type="hidden" name="action" value="feedback"><input type="hidden" name="video_id"><input type="hidden" name="visualizacao_id"><input type="hidden" name="nota" value="0"><div><span class="eyebrow blue">Sua avaliação</span><h3>Como foi este treinamento?</h3><p>Seu retorno ajuda a melhorar os próximos conteúdos.</p></div><div class="rating-buttons" data-rating aria-label="Nota do vídeo"><?php for($star=1;$star<=5;$star++): ?><button type="button" data-rating-value="<?= $star ?>" aria-label="<?= $star ?> estrela<?= $star>1?'s':'' ?>"><i class="bi bi-star-fill"></i></button><?php endfor; ?></div><label>Comentário<textarea name="comentario" rows="3" maxlength="2000" placeholder="O que foi mais útil?"></textarea></label><label>Sugestões de melhoria<textarea name="melhorias" rows="3" maxlength="2000" placeholder="O que podemos explicar melhor?"></textarea></label><button class="btn primary" type="submit"><i class="bi bi-send"></i> Enviar avaliação</button><div class="feedback-message" data-feedback-message></div></form></div></div></div>
