<section class="page-heading split">
    <div><span class="eyebrow blue">Gestão de conteúdo</span><h1>Modelos de veículos</h1><p>Cadastre as especificações técnicas e vincule cada modelo à sua família.</p></div>
    <div class="page-heading-actions">
        <?php if(can('models','update')): ?><button class="btn secondary" type="button" data-model-bulk-open disabled><i class="bi bi-pencil-square"></i> Editar selecionados</button><?php endif; ?>
        <?php if(can('models','create')): ?><button class="btn primary" data-model-create><i class="bi bi-plus-lg"></i> Novo modelo</button><?php endif; ?>
    </div>
</section>
<?php if ($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><i class="bi <?= $flash['type']==='success'?'bi-check-circle':'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>

<section class="panel">
    <form class="panel-head table-filters" method="get" action="<?= url('modelos') ?>" data-brand-family-filters>
        <div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($q) ?>" placeholder="Buscar modelo, motor ou potência..."></div>
        <div class="panel-filters">
            <select name="marca" data-filter-brand><option value="">Todas as marcas</option><?php foreach($brandOptions as $brand): ?><option value="<?= (int)$brand['id'] ?>" <?= $brandFilter===(int)$brand['id']?'selected':'' ?>><?= e($brand['nome']) ?></option><?php endforeach; ?></select>
            <select name="familia" data-filter-family><option value="">Todas as famílias</option><?php foreach($familyOptions as $option): ?><option value="<?= (int)$option['id'] ?>" data-brand="<?= (int)$option['marca_id'] ?>" <?= $familyFilter===(int)$option['id']?'selected':'' ?>><?= e($option['marca_nome'].' · '.$option['nome']) ?></option><?php endforeach; ?></select>
            <select name="status"><option value="">Todas as situações</option><option value="ativo" <?= $status==='ativo'?'selected':'' ?>>Ativos</option><option value="inativo" <?= $status==='inativo'?'selected':'' ?>>Inativos</option></select>
            <select name="ficha"><option value="">Todas as fichas</option><option value="com" <?= $fichaFilter==='com'?'selected':'' ?>>Com ficha técnica</option><option value="sem" <?= $fichaFilter==='sem'?'selected':'' ?>>Sem ficha técnica</option></select>
            <button class="btn secondary"><i class="bi bi-search"></i> Buscar</button><?php if($q!==''||$status!==''||$brandFilter||$familyFilter||$fichaFilter!==''): ?><a class="btn secondary" href="<?= url('modelos') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?>
        </div>
    </form>
    <div class="bulk-selection-bar" data-model-selection-bar hidden><div><i class="bi bi-check2-square"></i><strong><span data-model-selected-count>0</span> selecionado(s)</strong><small>As ações serão aplicadas somente aos modelos marcados nesta página.</small></div><button class="btn secondary" type="button" data-model-clear-selection><i class="bi bi-x-circle"></i> Limpar seleção</button></div>
    <div class="table-wrap"><table><thead><tr><th class="selection-column"><input type="checkbox" data-model-select-all aria-label="Selecionar todos os modelos desta página"></th><th>Modelo</th><th>Família</th><th>Especificações</th><th>Vínculos</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
    <?php if(!$models): ?><tr><td colspan="7"><div class="table-empty"><i class="bi bi-truck-front"></i><strong>Nenhum modelo encontrado</strong><span>Cadastre o primeiro modelo ou altere os filtros.</span></div></td></tr><?php endif; ?>
    <?php foreach($models as $model): $modelSpecs=json_decode((string)($model['especificacoes']??''),true);$modelSpecs=is_array($modelSpecs)?$modelSpecs:[];$wheelbase=(string)($modelSpecs['entre_eixos']??''); ?>
        <tr data-model-row>
            <td class="selection-column"><input type="checkbox" data-model-select value="<?= (int)$model['id'] ?>" data-name="<?= e($model['nome']) ?>" data-image="<?= $model['imagem']?e(url($model['imagem'])):'' ?>" aria-label="Selecionar <?= e($model['nome']) ?>"></td>
            <td><div class="entity-cell"><?php if($model['imagem']): ?><img src="<?= url($model['imagem']) ?>" alt="Imagem do modelo <?= e($model['nome']) ?>"><?php else: ?><span class="entity-placeholder"><i class="bi bi-truck-front"></i></span><?php endif; ?><div><strong><?= e($model['nome']) ?></strong><small><?= e($model['slug']) ?></small></div></div></td>
            <td><span class="pill"><?= e($model['familia_nome']) ?></span><small><?= e($model['marca_nome']) ?></small></td>
            <td><strong><?= e($model['potencia'] ?: 'Potência não informada') ?></strong><small><?= e($model['motor'] ?: 'Motor não informado') ?> · PBT <?= e($model['pbt'] ?: '—') ?> · Entre-eixos <?= e($wheelbase?:'—') ?></small><?php if($model['ficha_arquivo']||$model['ficha_url']): ?><a class="model-document-link" href="<?= e($model['ficha_arquivo']?url($model['ficha_arquivo']):$model['ficha_url']) ?>" target="_blank" rel="noopener"><i class="bi bi-file-earmark-pdf"></i> Especificações técnicas</a><?php else: ?><small class="document-missing"><i class="bi bi-file-earmark-x"></i> Sem ficha técnica</small><?php endif; ?></td>
            <td><span><?= (int)$model['videos'] ?> vídeo(s)</span><small><?= (int)$model['frota'] ?> veículo(s) em frotas</small></td>
            <td><span class="status <?= $model['ativo']?'active':'inactive' ?>"><?= $model['ativo']?'Ativo':'Inativo' ?></span></td>
            <td><div class="row-actions"><?php if($model['diretriz_arquivo']||$model['diretriz_url']): ?><a class="action-btn" href="<?= e($model['diretriz_arquivo']?url($model['diretriz_arquivo']):$model['diretriz_url']) ?>" target="_blank" rel="noopener" aria-label="Abrir diretrizes de <?= e($model['nome']) ?>"><i class="bi bi-journal-text"></i></a><?php endif; ?><?php if(can('models','update')): ?><button class="action-btn" data-model-edit data-id="<?= (int)$model['id'] ?>" data-family="<?= (int)$model['familia_id'] ?>" data-name="<?= e($model['nome']) ?>" data-description="<?= e($model['descricao']) ?>" data-image="<?= $model['imagem']?e(url($model['imagem'])):'' ?>" data-engine="<?= e($model['motor']) ?>" data-power="<?= e($model['potencia']) ?>" data-torque="<?= e($model['torque']) ?>" data-transmission="<?= e($model['transmissao']) ?>" data-pbt="<?= e($model['pbt']) ?>" data-wheelbase="<?= e($wheelbase) ?>" data-ficha-url="<?= e((string)$model['ficha_url']) ?>" data-ficha-name="<?= e($model['ficha_arquivo']?basename($model['ficha_arquivo']):'') ?>" data-diretriz-url="<?= e((string)$model['diretriz_url']) ?>" data-diretriz-name="<?= e($model['diretriz_arquivo']?basename($model['diretriz_arquivo']):'') ?>" data-active="<?= (int)$model['ativo'] ?>" aria-label="Editar <?= e($model['nome']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if(can('models','delete')): ?><button class="action-btn danger" data-model-delete data-id="<?= (int)$model['id'] ?>" data-name="<?= e($model['nome']) ?>" aria-label="Excluir <?= e($model['nome']) ?>"><i class="bi bi-trash"></i></button><?php endif; ?></div></td>
        </tr>
    <?php endforeach; ?>
    </tbody></table></div>
    <div class="pagination"><form method="get" action="<?= url('modelos') ?>" class="per-page"><input type="hidden" name="q" value="<?= e($q) ?>"><input type="hidden" name="status" value="<?= e($status) ?>"><input type="hidden" name="marca" value="<?= $brandFilter ?: '' ?>"><input type="hidden" name="familia" value="<?= $familyFilter ?: '' ?>"><input type="hidden" name="ficha" value="<?= e($fichaFilter) ?>"><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows?$offset+1:0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons" aria-label="Paginação"><?php if($page>1): ?><a href="<?= page_url('modelos',['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url('modelos',['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url('modelos',['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div>
</section>

<div class="modal" id="model-modal" aria-hidden="true"><div class="modal-dialog model-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Cadastro de veículo</span><h2 data-model-modal-title>Novo modelo</h2><p>Informe os dados comerciais, as especificações e os documentos técnicos.</p><form method="post" enctype="multipart/form-data" data-model-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id"><div class="form-grid">
    <label>Família<select name="familia_id" required><option value="">Selecione</option><?php foreach($familyOptions as $option): ?><option value="<?= (int)$option['id'] ?>"><?= e($option['marca_nome'].' · '.$option['nome']) ?></option><?php endforeach; ?></select></label><label>Nome do modelo<input name="nome" maxlength="120" required placeholder="Ex.: Constellation 17.210"></label>
    <label class="full">Descrição<textarea name="descricao" rows="3" maxlength="3000" placeholder="Aplicações e diferenciais do veículo"></textarea></label><label>Motor<input name="motor" maxlength="120" placeholder="Ex.: MAN D0834LF08"></label><label>Potência<input name="potencia" maxlength="100" placeholder="Ex.: 205 cv @ 2.300 rpm"></label><label>Torque<input name="torque" maxlength="100" placeholder="Ex.: 750 Nm @ 1.200–1.800 rpm"></label><label>Transmissão<input name="transmissao" maxlength="140" placeholder="Ex.: Eaton FS 5406-A"></label><label>PBT homologado<input name="pbt" maxlength="80" placeholder="Ex.: 16.000 kg"></label><label>Entre-eixos<input name="entre_eixos" maxlength="120" placeholder="Ex.: 3.000 ou 3.600 mm"></label><label class="check"><input type="checkbox" name="ativo" checked> Modelo ativo</label>
    <label class="full image-upload"><span class="image-preview" data-model-image-preview><i class="bi bi-image"></i></span><span><strong>Imagem do modelo</strong><small>JPG, PNG ou WEBP de até 5 MB</small><input type="file" name="imagem" accept="image/jpeg,image/png,image/webp" data-model-image-input></span></label>
    <fieldset class="full model-documents"><legend><i class="bi bi-file-earmark-pdf"></i> Documentos técnicos</legend><p>Você pode enviar o PDF ou informar o endereço oficial. O arquivo enviado fica salvo na pasta do sistema.</p><div class="document-grid"><label>Ficha técnica completa<input type="file" name="ficha_tecnica" accept="application/pdf"><small data-ficha-current>Nenhum arquivo selecionado</small></label><label>URL oficial da ficha<input type="url" name="ficha_url" maxlength="700" placeholder="https://..."></label><label>Diretrizes de implementação<input type="file" name="diretriz_implementacao" accept="application/pdf"><small data-diretriz-current>Nenhum arquivo selecionado</small></label><label>URL oficial das diretrizes<input type="url" name="diretriz_url" maxlength="700" placeholder="https://..."></label></div></fieldset>
</div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar modelo</button></div></form></div></div></div>

<div class="modal" id="bulk-model-modal" aria-hidden="true"><div class="modal-dialog bulk-model-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Ações em massa</span><h2>Editar modelos selecionados</h2><p>Escolha uma ação. Nenhum campo fora da ação selecionada será modificado.</p><form method="post" enctype="multipart/form-data" data-model-bulk-form><?= csrf_field() ?><input type="hidden" name="action" value="bulk_update"><div data-model-bulk-ids></div><div class="form-grid">
    <label class="full">Ação<select name="bulk_operation" data-model-bulk-operation required><option value="">Selecione a ação</option><option value="activate">Ativar modelos</option><option value="deactivate">Inativar modelos</option><option value="move_family">Transferir para outra família</option><option value="technical">Alterar uma informação técnica</option><option value="images">Trocar imagens individualmente</option></select></label>
    <div class="full bulk-operation-panel" data-bulk-panel="move_family" hidden><label>Nova família<select name="bulk_family_id"><option value="">Selecione</option><?php foreach($familyOptions as $option): ?><option value="<?= (int)$option['id'] ?>"><?= e($option['marca_nome'].' · '.$option['nome']) ?></option><?php endforeach; ?></select></label></div>
    <div class="full bulk-operation-panel bulk-technical-fields" data-bulk-panel="technical" hidden><label>Informação<select name="bulk_field"><option value="descricao">Descrição</option><option value="motor">Motor</option><option value="potencia">Potência</option><option value="torque">Torque</option><option value="transmissao">Transmissão</option><option value="pbt">PBT / capacidade</option><option value="entre_eixos">Entre-eixos</option></select></label><label>Novo valor<input name="bulk_value" maxlength="3000" placeholder="Valor que será aplicado aos selecionados"></label></div>
    <div class="full bulk-operation-panel" data-bulk-panel="images" hidden><div class="bulk-image-list" data-model-bulk-images></div></div>
</div><div class="bulk-confirm-note"><i class="bi bi-info-circle"></i><span>A operação será aplicada a <strong data-model-bulk-total>0</strong> modelo(s). Revise antes de confirmar.</span></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check2-all"></i> Aplicar alterações</button></div></form></div></div></div>

<div class="modal" id="delete-model-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-trash"></i></span><h2>Excluir modelo?</h2><p>Você está prestes a excluir <strong data-delete-model-name></strong>. Modelos vinculados a vídeos ou frotas não poderão ser excluídos.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-model-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger"><i class="bi bi-trash"></i> Excluir modelo</button></div></form></div></div></div>
