<?php
$profiles=$access['profiles']??[];$resourceLabels=['dashboard'=>'Visão geral','library'=>'Biblioteca','fleet'=>'Frotas','brands'=>'Marcas','families'=>'Famílias','models'=>'Modelos','categories'=>'Categorias','subcategories'=>'Subcategorias','videos'=>'Vídeos','emission_standards'=>'Normas de emissões','organizations'=>'Empresas VWCO','clients'=>'Clientes','client_links'=>'Vínculos de atendimento','users'=>'Usuários','permissions'=>'Perfis e permissões','reports'=>'Relatórios','feedback'=>'Feedbacks','locations'=>'Estados e cidades'];$actionLabels=['view'=>'Visualizar','create'=>'Cadastrar','update'=>'Editar','delete'=>'Excluir'];
?>
<section class="page-heading split"><div><span class="eyebrow blue">RBAC por empresa</span><h1>Perfis e acessos</h1><p>Defina o que cada perfil pode visualizar, cadastrar, editar e excluir.</p></div><?php if(can('permissions','create')): ?><button class="btn primary" data-profile-create><i class="bi bi-shield-plus"></i> Novo perfil</button><?php endif; ?></section>
<?php if($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><i class="bi <?= $flash['type']==='success'?'bi-check-circle':'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Perfil</th><th>Escopo</th><th>Nível</th><th>Usuários</th><th>Gerencia usuários</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
<?php foreach($profiles as $profile): $payload=['id'=>(int)$profile['id'],'nome'=>$profile['nome'],'empresa_id'=>$profile['empresa_id'],'nivel'=>(int)$profile['nivel'],'gerencia_usuarios'=>(int)$profile['pode_gerenciar_usuarios'],'ativo'=>(int)$profile['ativo'],'permissoes'=>array_values(array_filter(explode(',',(string)$profile['permission_ids'])))] ?>
<tr><td><div class="entity-cell"><span class="entity-placeholder"><i class="bi bi-shield-check"></i></span><div><strong><?= e($profile['nome']) ?></strong><small><?= $profile['sistema']?'Perfil padrão do sistema':'Perfil personalizado' ?></small></div></div></td><td><span class="pill"><?= e($profile['empresa_nome']?:($profile['escopo']==='global'?'Todas as empresas':'Modelo global')) ?></span></td><td><strong><?= (int)$profile['nivel'] ?></strong><small>Hierarquia de atribuição</small></td><td><?= (int)$profile['usuarios'] ?></td><td><?= $profile['pode_gerenciar_usuarios']?'<span class="status active">Sim</span>':'<span class="status inactive">Não</span>' ?></td><td><span class="status <?= $profile['ativo']?'active':'inactive' ?>"><?= $profile['ativo']?'Ativo':'Inativo' ?></span></td><td><div class="row-actions"><?php if(can('permissions','update')&&$profile['slug']!=='administrador'): ?><button class="action-btn" data-profile-edit data-profile="<?= e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>" aria-label="Editar <?= e($profile['nome']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if(can('permissions','delete')&&!$profile['sistema']): ?><button class="action-btn danger" data-profile-delete data-id="<?= (int)$profile['id'] ?>" data-name="<?= e($profile['nome']) ?>" aria-label="Excluir <?= e($profile['nome']) ?>"><i class="bi bi-trash"></i></button><?php endif; ?></div></td></tr>
<?php endforeach; ?></tbody></table></div></section>

<div class="modal" id="profile-modal" aria-hidden="true"><div class="modal-dialog permission-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Matriz de permissões</span><h2 data-profile-modal-title>Novo perfil</h2><p>O nível impede que um administrador conceda um perfil superior ao próprio.</p><form method="post" data-profile-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id"><div class="form-grid"><label>Nome do perfil<input name="nome" maxlength="80" required></label><label>Nível hierárquico<input type="number" name="nivel" min="1" max="99" value="50" required></label><?php if(is_master()): ?><label class="full">Empresa específica<select name="empresa_id"><option value="">Perfil disponível globalmente</option><?php foreach($access['companyOptions']??[] as $company): ?><option value="<?= (int)$company['id'] ?>"><?= e($company['nome_fantasia']) ?></option><?php endforeach; ?></select></label><?php endif; ?><label class="check"><input type="checkbox" name="gerencia_usuarios"> Pode gerenciar usuários</label><label class="check"><input type="checkbox" name="ativo" checked> Perfil ativo</label>
<fieldset class="full permission-fieldset"><legend>Permissões por página</legend><div class="permission-matrix"><div class="permission-head"><strong>Recurso</strong><?php foreach($actionLabels as $actionLabel): ?><strong><?= e($actionLabel) ?></strong><?php endforeach; ?></div><?php foreach($access['permissionGroups']??[] as $resource=>$permissions): ?><div class="permission-row"><span><?= e($resourceLabels[$resource]??ucfirst($resource)) ?></span><?php $indexed=[];foreach($permissions as $permission)$indexed[$permission['acao']]=$permission;foreach(array_keys($actionLabels) as $action): $permission=$indexed[$action]??null; ?><label title="<?= $permission?e($permission['descricao']):'' ?>"><?php if($permission): ?><input type="checkbox" name="permissoes[]" value="<?= (int)$permission['id'] ?>"><i class="bi bi-check"></i><?php endif; ?></label><?php endforeach; ?></div><?php endforeach; ?></div></fieldset></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar perfil</button></div></form></div></div></div>
<div class="modal" id="delete-profile-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-trash"></i></span><h2>Excluir perfil?</h2><p>O perfil <strong data-delete-profile-name></strong> só poderá ser excluído se não possuir usuários.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-profile-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger">Excluir perfil</button></div></form></div></div></div>
