<?php
$report=$reports??[];$metrics=$report['metrics']??[];
$queryBase=['inicio'=>$report['start']??'','fim'=>$report['end']??'','cliente'=>$report['clientFilter']??0,'categoria'=>$report['categoryFilter']??0,'video'=>$report['videoFilter']??0,'usuarios_por_pagina'=>$report['userPerPage']??10];
$number=static fn(mixed $value):string=>number_format((float)$value,0,',','.');
$decimal=static fn(mixed $value):string=>number_format((float)$value,1,',','.');
?>
<section class="page-heading split report-heading"><div><span class="eyebrow blue">Inteligência de treinamento</span><h1>Relatórios e avaliações</h1><p>Acompanhe alcance, conclusão, engajamento e oportunidades de melhoria dentro do seu escopo de acesso.</p></div><a class="btn secondary" href="<?= page_url('relatorios',$queryBase+['exportar'=>'csv']) ?>"><i class="bi bi-file-earmark-spreadsheet"></i> Exportar CSV</a></section>

<form class="report-filters" method="get" action="<?= url('relatorios') ?>">
<label>Período inicial<input type="date" name="inicio" value="<?= e($report['start']??'') ?>"></label><label>Período final<input type="date" name="fim" value="<?= e($report['end']??'') ?>"></label>
<?php if(($report['clientOptions']??[])&&(user()['active_company_type']??'')!=='cliente'): ?><label>Cliente<select name="cliente"><option value="">Todos com atividade</option><?php foreach($report['clientOptions'] as $option): ?><option value="<?= (int)$option['id'] ?>" <?= (int)$report['clientFilter']===(int)$option['id']?'selected':'' ?>><?= e($option['nome_fantasia']) ?></option><?php endforeach; ?></select></label><?php endif; ?>
<label>Categoria<select name="categoria" <?= ($report['categoryOptions']??[])?'':'disabled' ?>><option value=""><?= ($report['categoryOptions']??[])?'Todas as categorias':'Nenhuma categoria com atividade' ?></option><?php foreach($report['categoryOptions']??[] as $option): ?><option value="<?= (int)$option['id'] ?>" <?= (int)$report['categoryFilter']===(int)$option['id']?'selected':'' ?>><?= e($option['nome']) ?></option><?php endforeach; ?></select></label>
<label>Treinamento<select name="video" <?= ($report['videoOptions']??[])?'':'disabled' ?>><option value=""><?= ($report['videoOptions']??[])?'Todos os treinamentos':'Nenhum treinamento com atividade' ?></option><?php foreach($report['videoOptions']??[] as $option): ?><option value="<?= (int)$option['id'] ?>" <?= (int)$report['videoFilter']===(int)$option['id']?'selected':'' ?>><?= e($option['titulo']) ?></option><?php endforeach; ?></select></label>
<button class="btn primary"><i class="bi bi-funnel"></i> Aplicar filtros</button><a class="btn secondary" href="<?= url('relatorios') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a>
</form>

<section class="report-metrics">
<article><span class="report-metric-icon blue"><i class="bi bi-play-circle"></i></span><div><small>Visualizações iniciadas</small><strong><?= $number($metrics['visualizacoes']??0) ?></strong><em><?= $number($metrics['usuarios']??0) ?> usuário(s) único(s)</em></div></article>
<article><span class="report-metric-icon green"><i class="bi bi-check-circle"></i></span><div><small>Treinamentos concluídos</small><strong><?= $number($metrics['conclusoes']??0) ?></strong><em><?= $decimal($metrics['taxa_conclusao']??0) ?>% de conclusão</em></div></article>
<article><span class="report-metric-icon orange"><i class="bi bi-graph-up-arrow"></i></span><div><small>Progresso médio</small><strong><?= $decimal($metrics['progresso_medio']??0) ?>%</strong><em>Em todas as visualizações</em></div></article>
<article><span class="report-metric-icon violet"><i class="bi bi-star"></i></span><div><small>Avaliação média</small><strong><?= ($metrics['nota_media']??null)!==null?$decimal($metrics['nota_media']).'/5':'—' ?></strong><em><?= $number($metrics['avaliacoes']??0) ?> avaliação(ões)</em></div></article>
</section>

<section class="report-overview-grid">
<article class="report-card"><div class="report-card-head"><div><span class="eyebrow blue">Evolução</span><h2>Atividade no período</h2></div><small>Visualizações por dia</small></div><?php if($report['trend']??[]): ?><div class="report-chart" role="img" aria-label="Gráfico de visualizações por dia"><?php foreach($report['trend'] as $point): ?><div class="report-bar-item" title="<?= date('d/m/Y',strtotime($point['dia'])) ?>: <?= (int)$point['visualizacoes'] ?> visualizações"><div class="report-bar"><i style="height:<?= max(8,round((int)$point['visualizacoes']*100/$report['trendMax'])) ?>%"></i></div><span><?= date('d/m',strtotime($point['dia'])) ?></span></div><?php endforeach; ?></div><?php else: ?><div class="report-empty compact"><i class="bi bi-bar-chart"></i><strong>Sem atividade no período</strong><span>Ajuste os filtros para consultar outro intervalo.</span></div><?php endif; ?></article>
<article class="report-card report-insight"><span class="eyebrow blue">Leitura rápida</span><h2>Indicadores do período</h2><div><span><i class="bi bi-people"></i><strong><?= $number($metrics['usuarios']??0) ?></strong><small>pessoas alcançadas</small></span><span><i class="bi bi-percent"></i><strong><?= $decimal($metrics['taxa_conclusao']??0) ?>%</strong><small>das sessões concluídas</small></span><span><i class="bi bi-chat-square-heart"></i><strong><?= $number($metrics['avaliacoes']??0) ?></strong><small>feedbacks recebidos</small></span></div></article>
</section>

<section class="report-section"><div class="section-heading"><div><span class="eyebrow blue">Conteúdo</span><h2>Desempenho dos treinamentos</h2><p>Os dez conteúdos com maior atividade dentro dos filtros escolhidos.</p></div></div><div class="panel"><div class="table-wrap"><table class="report-table"><thead><tr><th>Treinamento</th><th>Visualizações</th><th>Usuários</th><th>Conclusões</th><th>Progresso</th><th>Nota</th></tr></thead><tbody><?php if(!($report['topVideos']??[])): ?><tr><td colspan="6"><div class="table-empty"><i class="bi bi-camera-video"></i><strong>Nenhum treinamento encontrado</strong><span>Não há visualizações para os filtros selecionados.</span></div></td></tr><?php endif; ?><?php foreach($report['topVideos']??[] as $video): ?><tr><td><strong><?= e($video['titulo']) ?></strong><small><?= e($video['categoria']) ?></small></td><td><?= $number($video['visualizacoes']) ?></td><td><?= $number($video['usuarios']) ?></td><td><strong><?= $number($video['conclusoes']) ?></strong><small><?= (int)$video['visualizacoes']? $decimal((int)$video['conclusoes']*100/(int)$video['visualizacoes']).'%':'0,0%' ?></small></td><td><span class="report-progress"><i style="width:<?= min(100,(float)$video['progresso_medio']) ?>%"></i></span><small><?= $decimal($video['progresso_medio']) ?>%</small></td><td><?= $video['nota_media']!==null?'<span class="report-rating"><i class="bi bi-star-fill"></i> '.$decimal($video['nota_media']).'</span>':'<small>Sem nota</small>' ?></td></tr><?php endforeach; ?></tbody></table></div></div></section>

<section class="report-section"><div class="section-heading"><div><span class="eyebrow blue">Pessoas</span><h2>Engajamento por usuário</h2><p>Participação, conclusão e progresso de cada pessoa.</p></div></div><div class="panel"><div class="table-wrap"><table class="report-table"><thead><tr><th>Usuário</th><th>Empresa</th><th>Vídeos acessados</th><th>Visualizações</th><th>Conclusões</th><th>Progresso médio</th><th>Última atividade</th></tr></thead><tbody><?php if(!($report['users']??[])): ?><tr><td colspan="7"><div class="table-empty"><i class="bi bi-people"></i><strong>Nenhum usuário encontrado</strong><span>Ainda não há atividade registrada neste período.</span></div></td></tr><?php endif; ?><?php foreach($report['users']??[] as $row): ?><tr><td><strong><?= e($row['nome']) ?></strong><small><?= e($row['email']) ?></small></td><td><?= e($row['empresa']?:'Empresa não identificada') ?></td><td><?= $number($row['videos']) ?></td><td><?= $number($row['visualizacoes']) ?></td><td><?= $number($row['conclusoes']) ?></td><td><span class="report-progress"><i style="width:<?= min(100,(float)$row['progresso_medio']) ?>%"></i></span><small><?= $decimal($row['progresso_medio']) ?>%</small></td><td><?= date('d/m/Y H:i',strtotime($row['ultimo_acesso'])) ?></td></tr><?php endforeach; ?></tbody></table></div><div class="pagination"><form method="get" action="<?= url('relatorios') ?>" class="per-page"><?php foreach($queryBase as $name=>$value): ?><?php if($name!=='usuarios_por_pagina'): ?><input type="hidden" name="<?= e($name) ?>" value="<?= e((string)$value) ?>"><?php endif; ?><?php endforeach; ?><label>Mostrar <select name="usuarios_por_pagina" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= (int)$report['userPerPage']===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= ($report['userTotal']??0)?(int)$report['userOffset']+1:0 ?>–<?= min((int)$report['userOffset']+(int)$report['userPerPage'],(int)$report['userTotal']) ?> de <?= (int)($report['userTotal']??0) ?></span><nav class="page-buttons" aria-label="Paginação do engajamento"><?php if(($report['userPage']??1)>1): ?><a href="<?= page_url('relatorios',$queryBase+['usuarios_pagina'=>$report['userPage']-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,(int)$report['userPage']-2);$p<=min((int)$report['userPages'],(int)$report['userPage']+2);$p++): ?><a class="<?= $p===(int)$report['userPage']?'active':'' ?>" href="<?= page_url('relatorios',$queryBase+['usuarios_pagina'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if(($report['userPage']??1)<($report['userPages']??1)): ?><a href="<?= page_url('relatorios',$queryBase+['usuarios_pagina'=>$report['userPage']+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div></div></section>

<section class="report-section"><div class="section-heading"><div><span class="eyebrow blue">Qualidade</span><h2>Avaliações e oportunidades de melhoria</h2><p>Comentários enviados após a conclusão dos treinamentos.</p></div></div><div class="feedback-report-grid"><?php if(!($report['feedbacks']??[])): ?><div class="report-card report-empty"><i class="bi bi-chat-square-text"></i><strong>Nenhuma avaliação encontrada</strong><span>As avaliações aparecerão aqui depois que os usuários concluírem os vídeos.</span></div><?php endif; ?><?php foreach($report['feedbacks']??[] as $feedback): ?><article class="feedback-report-card"><header><div><strong><?= e($feedback['usuario']) ?></strong><small><?= e($feedback['empresa']?:'Empresa não identificada') ?></small></div><span><i class="bi bi-star-fill"></i> <?= (int)$feedback['nota'] ?>/5</span></header><h3><?= e($feedback['titulo']) ?></h3><?php if($feedback['comentario']): ?><p><?= nl2br(e($feedback['comentario'])) ?></p><?php endif; ?><?php if($feedback['melhorias']): ?><div><small><i class="bi bi-lightbulb"></i> Sugestão de melhoria</small><p><?= nl2br(e($feedback['melhorias'])) ?></p></div><?php endif; ?><footer><?= date('d/m/Y H:i',strtotime($feedback['criado_em'])) ?></footer></article><?php endforeach; ?></div></section>
