<?php
$desk=$serviceDesk??[];$statuses=service_desk_statuses();$types=service_desk_types();$groups=service_desk_groups();$origins=service_desk_origins();
$selected=$desk['selected']??null;$internal=service_desk_internal_user();$activeTab=(string)($_GET['tab']??'context');if(!in_array($activeTab,['context','timeline','solutions'],true))$activeTab='context';
?>
<?php if(!($desk['ready']??false)): ?>
<section class="empty-state service-migration"><i class="bi bi-database-exclamation"></i><h2>Estrutura profissional do Service Desk pendente</h2><p>Execute a migração <strong>20260730_023_service_desk_prioridades_workflow.sql</strong> no banco da HostGator.</p></section>
<?php else: ?>
<section class="service-hero">
    <div><span class="eyebrow">Voz do cliente</span><h1><?= $internal?'Service Desk de produto':'Meus relatos' ?></h1><p><?= $internal?'Priorize incidentes e requisições, controle SLAs e preserve todas as interações e decisões.':'Acompanhe os relatos enviados e o retorno dos times responsáveis.' ?></p></div>
    <button type="button" class="primary-button" data-assistant-open><i class="bi bi-mic"></i> Novo relato pelo assistente</button>
</section>

<section class="service-kpis"><?php foreach(['novo','transferido','em_tratamento','possivel_solucao','finalizado'] as $key): ?><article class="<?= e($key) ?>"><span><?= (int)($desk['counts'][$key]??0) ?></span><small><?= e($statuses[$key]) ?></small></article><?php endforeach; ?></section>

<section class="panel service-list">
    <form class="panel-head table-filters service-filters" method="get" action="<?= url('service-desk') ?>">
        <div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($desk['q']??'') ?>" placeholder="Buscar protocolo, título ou relato..."></div>
        <div class="panel-filters">
            <select name="status"><option value="">Todos os status</option><?php foreach($statuses as $value=>$label): if(empty($desk['counts'][$value]))continue; ?><option value="<?= e($value) ?>" <?= ($desk['status_filter']??'')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select>
            <select name="prioridade"><option value="">Todas as prioridades</option><?php foreach($desk['filter_priorities'] as $priority): ?><option value="<?= (int)$priority['id'] ?>" <?= (int)($desk['priority_filter']??0)===(int)$priority['id']?'selected':'' ?>><?= e($priority['codigo'].' · '.$priority['nome']) ?></option><?php endforeach; ?></select>
            <select name="grupo"><option value="">Todos os grupos</option><?php foreach($groups as $value=>$label): if(empty($desk['filter_groups'][$value]))continue; ?><option value="<?= e($value) ?>" <?= ($desk['group_filter']??'')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select>
            <select name="categoria"><option value="">Todas as categorias</option><?php foreach($desk['filter_categories'] as $category): ?><option value="<?= (int)$category['id'] ?>" <?= (int)($desk['category_filter']??0)===(int)$category['id']?'selected':'' ?>><?= e($category['nome']) ?></option><?php endforeach; ?></select>
            <?php if($internal): ?><select name="setor"><option value="">Todos os setores</option><?php foreach($desk['filter_sectors'] as $sector): ?><option value="<?= (int)$sector['id'] ?>" <?= (int)($desk['sector_filter']??0)===(int)$sector['id']?'selected':'' ?>><?= e($sector['nome']) ?></option><?php endforeach; ?></select><?php endif; ?>
            <select name="tipo"><option value="">Todos os tipos</option><?php foreach($types as $value=>$label): if(empty($desk['filter_types'][$value]))continue; ?><option value="<?= e($value) ?>" <?= ($desk['type_filter']??'')===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select>
            <button class="btn secondary" type="submit"><i class="bi bi-search"></i> Buscar</button>
            <a class="btn secondary filter-clear" href="<?= url('service-desk') ?>" aria-label="Limpar filtros" title="Limpar filtros"><i class="bi bi-x-lg"></i></a>
        </div>
    </form>
    <div class="table-wrap"><table><thead><tr><th>Chamado</th><th>Relato</th><?php if($internal): ?><th>Cliente</th><?php endif; ?><th>Origem</th><th>Classificação</th><th>SLA</th><th>Status</th><th></th></tr></thead><tbody>
    <?php if(!$desk['reports']): ?><tr><td colspan="<?= $internal?8:7 ?>"><div class="table-empty"><i class="bi bi-inbox"></i><strong>Nenhum chamado encontrado</strong><span>Limpe os filtros ou registre um novo relato pelo assistente.</span></div></td></tr><?php endif; ?>
    <?php foreach($desk['reports'] as $report):
        $resolutionOverdue=!in_array($report['status'],['finalizado','cancelado'],true)&&$report['sla_resolucao_em']&&strtotime($report['sla_resolucao_em'])<time();$resolutionLate=$report['finalizado_em']&&$report['sla_resolucao_em']&&strtotime($report['finalizado_em'])>strtotime($report['sla_resolucao_em']);
        $firstOverdue=!$report['primeira_resposta_em']&&$report['sla_primeira_resposta_em']&&strtotime($report['sla_primeira_resposta_em'])<time();$firstLate=$report['primeira_resposta_em']&&$report['sla_primeira_resposta_em']&&strtotime($report['primeira_resposta_em'])>strtotime($report['sla_primeira_resposta_em']);
        $vehicle=implode(' · ',array_filter([$report['marca_nome'],$report['familia_nome'],$report['modelo_nome']]));
    ?><tr>
        <td><div class="service-ticket-code"><strong><?= e($report['protocolo']) ?></strong><?php if($report['recorrente']): ?><i class="bi bi-copy" title="Recorrente"></i><?php endif; ?></div><small><?= e($groups[$report['grupo']]??ucfirst($report['grupo'])) ?> · <?= date('d/m/Y H:i',strtotime($report['criado_em'])) ?></small></td>
        <td><span class="service-type <?= e($report['tipo']) ?>"><?= e($types[$report['tipo']]??$report['tipo']) ?></span><strong><?= e($report['titulo']) ?></strong><small><?= e(mb_strimwidth($report['relato_original'],0,105,'…')) ?></small></td>
        <?php if($internal): ?><td><?= e($report['empresa_nome']?:'Sem empresa') ?><small><?= e($report['usuario_nome']) ?></small></td><?php endif; ?>
        <td><strong><?= e($origins[$report['origem_item']]??ucfirst($report['origem_item'])) ?></strong><small><?= e($report['origem_item']==='veiculo'?($vehicle?:'Não identificado'):'Drive Learn / web') ?></small></td>
        <td><?php if($report['prioridade_codigo']): ?><span class="service-priority" style="--priority-color:<?= e($report['prioridade_cor']) ?>"><?= e($report['prioridade_codigo']) ?></span><?php endif; ?><strong><?= e($report['categoria_nome']?:'A classificar') ?></strong><small><?= e($report['setor_nome']?:'Triagem') ?></small></td>
        <td><div class="service-sla"><small class="<?= ($firstOverdue||$firstLate)?'overdue':'' ?>"><i class="bi bi-chat-dots"></i> <?= $report['primeira_resposta_em']?($firstLate?'Interação fora do SLA':'Interação no SLA'):($report['sla_primeira_resposta_em']?date('d/m H:i',strtotime($report['sla_primeira_resposta_em'])):'—') ?></small><small class="<?= ($resolutionOverdue||$resolutionLate)?'overdue':'' ?>"><i class="bi bi-stopwatch"></i> <?= $report['finalizado_em']?($resolutionLate?'Resolução fora do SLA':'Resolução no SLA'):($report['sla_resolucao_em']?date('d/m H:i',strtotime($report['sla_resolucao_em'])):'—') ?></small></div></td>
        <td><span class="service-status <?= e($report['status']) ?>"><?= e($statuses[$report['status']]??$report['status']) ?></span></td>
        <td><a class="icon-btn" href="<?= url('service-desk?id='.(int)$report['id']) ?>" aria-label="Abrir chamado"><i class="bi bi-chevron-right"></i></a></td>
    </tr><?php endforeach; ?></tbody></table></div>
    <?php $page=$desk['page'];$perPage=$desk['per_page'];$offset=$desk['offset'];$totalRows=$desk['total'];$totalPages=$desk['pages']; ?><div class="pagination"><form method="get" action="<?= url('service-desk') ?>" class="per-page"><?php foreach(['q','status_filter','type_filter','sector_filter','priority_filter','category_filter','group_filter'] as $filterKey): $queryName=['status_filter'=>'status','type_filter'=>'tipo','sector_filter'=>'setor','priority_filter'=>'prioridade','category_filter'=>'categoria','group_filter'=>'grupo'][$filterKey]??$filterKey; ?><input type="hidden" name="<?= e($queryName) ?>" value="<?= e((string)($desk[$filterKey]??'')) ?>"><?php endforeach; ?><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows?$offset+1:0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons"><?php if($page>1): ?><a href="<?= page_url('service-desk',['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url('service-desk',['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url('service-desk',['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div>
</section>

<?php if($selected): ?>
<div class="service-detail-backdrop"><section class="service-detail-modal service-detail" data-service-detail>
    <header><div><span class="eyebrow"><?= e($selected['protocolo']) ?> · <?= e($groups[$selected['grupo']]??ucfirst($selected['grupo'])) ?></span><h2><?= e($selected['titulo']) ?></h2><p><?= e(($selected['empresa_nome']?:'Sem empresa').' · '.$selected['usuario_nome']) ?></p></div><div class="service-ticket-code"><?php if($selected['prioridade_codigo']): ?><span class="service-priority" style="--priority-color:<?= e($selected['prioridade_cor']) ?>"><?= e($selected['prioridade_codigo']) ?></span><?php endif; ?><a class="modal-close" href="<?= url('service-desk') ?>" aria-label="Fechar"><i class="bi bi-x-lg"></i></a></div></header>
    <?php if($internal&&can('service_desk','update')): ?><form class="service-workflow" method="post" action="<?= url('service-desk') ?>"><?= csrf_field() ?><input type="hidden" name="action" value="update_report"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><div class="service-workflow-grid">
        <label>Tipo<select name="tipo"><?php foreach($types as $value=>$label): ?><option value="<?= e($value) ?>" <?= $selected['tipo']===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
        <label>Prioridade<select name="prioridade_id" required><?php foreach($desk['priorities'] as $priority): ?><option value="<?= (int)$priority['id'] ?>" <?= (int)$selected['prioridade_id']===(int)$priority['id']?'selected':'' ?>><?= e($priority['codigo'].' · '.$priority['nome']) ?></option><?php endforeach; ?></select></label>
        <label>Categoria<select name="categoria_id" required><?php foreach($desk['categories'] as $category): ?><option value="<?= (int)$category['id'] ?>" <?= (int)$selected['categoria_id']===(int)$category['id']?'selected':'' ?>><?= e($category['nome']) ?></option><?php endforeach; ?></select></label>
        <label>Status<select name="status"><?php foreach($statuses as $value=>$label): ?><option value="<?= e($value) ?>" <?= $selected['status']===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
        <label>Setor responsável<select name="setor_id"><option value="">Triagem</option><?php foreach($desk['sectors'] as $sector): ?><option value="<?= (int)$sector['id'] ?>" <?= (int)$selected['setor_id']===(int)$sector['id']?'selected':'' ?>><?= e($sector['nome']) ?></option><?php endforeach; ?></select></label>
        <label>Responsável<select name="responsavel_id"><option value="">Não atribuído</option><?php foreach($desk['users'] as $account): ?><option value="<?= (int)$account['id'] ?>" <?= (int)$selected['responsavel_id']===(int)$account['id']?'selected':'' ?>><?= e($account['nome']) ?></option><?php endforeach; ?></select></label>
        <label class="check-row"><input type="checkbox" name="recorrente" value="1" <?= $selected['recorrente']?'checked':'' ?> data-service-recurring> Ocorrência recorrente</label>
        <label class="wide" data-service-parent <?= $selected['recorrente']?'':'hidden' ?>>Ticket pai de referência<select name="ticket_pai_id"><option value="">Selecione o ticket pai</option><?php foreach($desk['parent_tickets'] as $parent): if((int)$parent['id']===(int)$selected['id'])continue; ?><option value="<?= (int)$parent['id'] ?>" <?= (int)$selected['ticket_pai_id']===(int)$parent['id']?'selected':'' ?>><?= e($parent['protocolo'].' · '.$parent['titulo'].' · '.($statuses[$parent['status']]??$parent['status'])) ?></option><?php endforeach; ?></select></label>
        <label class="wide">Comentário da alteração<textarea name="observacao" rows="2" placeholder="Explique a transferência, recategorização ou mudança de prioridade..."></textarea></label>
    </div><div class="service-workflow-actions"><span class="service-parent-note" <?= $selected['ticket_pai_protocolo']?'':'hidden' ?>><i class="bi bi-copy"></i> Referência atual: <?= e($selected['ticket_pai_protocolo']??'') ?></span><button class="primary-button"><i class="bi bi-check2-circle"></i> Salvar andamento</button></div></form><?php endif; ?>
    <nav class="service-tabs" aria-label="Detalhes do chamado"><button type="button" class="<?= $activeTab==='context'?'active':'' ?>" data-service-tab="context"><i class="bi bi-card-text"></i> Contexto</button><button type="button" class="<?= $activeTab==='timeline'?'active':'' ?>" data-service-tab="timeline"><i class="bi bi-chat-left-dots"></i> Histórico e interações</button><button type="button" class="<?= $activeTab==='solutions'?'active':'' ?>" data-service-tab="solutions"><i class="bi bi-lightbulb"></i> Soluções</button></nav>
    <section class="service-tab-panel <?= $activeTab==='context'?'active':'' ?>" data-service-panel="context"><div class="service-context-grid"><article class="service-report-text"><h3>Relato confirmado</h3><p><?= nl2br(e($selected['relato_original'])) ?></p><div><span><?= e($selected['categoria_nome']?:'A classificar') ?></span><span><?= e($origins[$selected['origem_item']]??ucfirst($selected['origem_item'])) ?></span><?php if($selected['origem_item']==='veiculo'): ?><span><?= e(implode(' · ',array_filter([$selected['marca_nome'],$selected['familia_nome'],$selected['modelo_nome']]))?:'Veículo não identificado') ?></span><?php endif; ?></div></article><aside class="service-meta-card"><dl><dt>Grupo</dt><dd><?= e($groups[$selected['grupo']]??$selected['grupo']) ?></dd><dt>Status</dt><dd><?= e($statuses[$selected['status']]??$selected['status']) ?></dd><dt>Setor</dt><dd><?= e($selected['setor_nome']?:'Triagem') ?></dd><dt>Responsável</dt><dd><?= e($selected['responsavel_nome']?:'Não atribuído') ?></dd><dt>Primeira interação</dt><dd><?= $selected['primeira_resposta_em']?date('d/m/Y H:i',strtotime($selected['primeira_resposta_em'])):'Aguardando' ?></dd><dt>SLA de resolução</dt><dd><?= $selected['sla_resolucao_em']?date('d/m/Y H:i',strtotime($selected['sla_resolucao_em'])):'Não definido' ?></dd><dt>Recorrência</dt><dd><?= $selected['recorrente']?'Sim'.($selected['ticket_pai_protocolo']?' · '.$selected['ticket_pai_protocolo']:''):'Não' ?></dd></dl></aside></div>
    <?php if($selected['status']==='finalizado'&&!($desk['satisfaction']??null)&&(int)$selected['usuario_id']===(int)(user()['id']??0)): ?><form class="service-compose" method="post" action="<?= url('service-desk') ?>"><?= csrf_field() ?><input type="hidden" name="action" value="satisfaction"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><h3>Avalie a solução</h3><div class="service-workflow-grid"><label>Nota<select name="nota"><?php for($i=5;$i>=1;$i--): ?><option value="<?= $i ?>"><?= $i ?> estrela<?= $i>1?'s':'' ?></option><?php endfor; ?></select></label><label class="check-row"><input type="checkbox" name="resolvido" value="1" checked> Minha necessidade foi resolvida</label><label class="wide">Comentário<textarea name="comentario" rows="2"></textarea></label></div><footer><button class="primary-button">Enviar avaliação</button></footer></form><?php endif; ?></section>
    <section class="service-tab-panel <?= $activeTab==='timeline'?'active':'' ?>" data-service-panel="timeline"><section class="service-timeline"><h3>Conversa e evolução do ticket</h3>
        <?php $timeline=[];foreach($desk['messages']??[] as $item)$timeline[]=['time'=>$item['criado_em'],'kind'=>$item['origem'],'icon'=>$item['origem']==='usuario'?'bi-person':'bi-chat-left-text','author'=>$item['usuario_nome']?:ucfirst($item['origem']),'text'=>$item['mensagem']];foreach($desk['history']??[] as $item){if($item['evento']==='interacao')continue;$timeline[]=['time'=>$item['criado_em'],'kind'=>'history','icon'=>'bi-arrow-repeat','author'=>$item['usuario_nome']?:'Sistema','text'=>($item['evento']?:'Atualização').($item['status_novo']?' · '.($statuses[$item['status_novo']]??$item['status_novo']):'').($item['observacao']?' · '.$item['observacao']:'')];}usort($timeline,static fn($a,$b)=>strcmp($a['time'],$b['time']));foreach($timeline as $item): ?><article class="<?= e($item['kind']) ?>"><i class="bi <?= e($item['icon']) ?>"></i><div><strong><?= e($item['author']) ?></strong><p><?= nl2br(e($item['text'])) ?></p><small><?= date('d/m/Y H:i',strtotime($item['time'])) ?></small></div></article><?php endforeach; ?>
    </section><?php if(($internal&&can('service_desk','update'))||(int)$selected['usuario_id']===(int)(user()['id']??0)): ?><form class="service-compose" method="post" action="<?= url('service-desk') ?>"><?= csrf_field() ?><input type="hidden" name="action" value="add_interaction"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><h3><?= $internal?'Registrar nova interação':'Adicionar comentário' ?></h3><textarea name="mensagem" rows="4" required placeholder="<?= $internal?'Registre o contato, diagnóstico, decisão ou retorno enviado ao cliente...':'Escreva uma informação complementar ou responda ao time responsável...' ?>"></textarea><footer><button class="primary-button"><i class="bi bi-send"></i> Adicionar ao histórico</button></footer></form><?php endif; ?></section>
    <section class="service-tab-panel <?= $activeTab==='solutions'?'active':'' ?>" data-service-panel="solutions"><div class="service-solutions-grid"><div class="service-solutions-list"><h3>Soluções propostas e aplicadas</h3><?php if(!($desk['solutions']??[])): ?><div class="table-empty"><i class="bi bi-lightbulb"></i><strong>Nenhuma solução registrada</strong><span>Registre hipóteses separadamente da solução efetivamente aplicada.</span></div><?php endif; ?><?php foreach($desk['solutions']??[] as $solution): ?><article class="service-solution"><header><span class="type <?= e($solution['tipo']) ?>"><?= $solution['tipo']==='aplicada'?'Solução aplicada':'Proposta' ?></span><small><?= date('d/m/Y H:i',strtotime($solution['criado_em'])) ?></small></header><p><?= e($solution['descricao']) ?></p><small>Por <?= e($solution['usuario_nome']?:'Sistema') ?></small></article><?php endforeach; ?></div><?php if($internal&&can('service_desk','update')): ?><form class="service-compose" method="post" action="<?= url('service-desk') ?>"><?= csrf_field() ?><input type="hidden" name="action" value="add_solution"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><h3>Adicionar solução</h3><label>Tipo<select name="tipo_solucao"><option value="proposta">Solução proposta</option><option value="aplicada">Solução aplicada</option></select></label><label>Descrição<textarea name="descricao_solucao" rows="7" required placeholder="Descreva a proposta, validação ou solução aplicada..."></textarea></label><button class="primary-button"><i class="bi bi-plus-lg"></i> Registrar solução</button></form><?php endif; ?></div></section>
</section></div>
<?php endif; ?>
<?php endif; ?>
