<?php
$priorityPage=$servicePriorities??[];$rows=$priorityPage['rows']??[];
?>
<section class="page-heading split"><div><span class="eyebrow blue">Base do Service Desk</span><h1>Prioridades e SLAs</h1><p>Defina o tempo da primeira interação e da resolução para cada nível de impacto.</p></div><?php if(can('service_priorities','create')): ?><button class="btn primary" data-priority-create><i class="bi bi-plus-lg"></i> Nova prioridade</button><?php endif; ?></section>
<?php if($flash): ?><div class="alert <?= $flash['type']==='success'?'success':'error' ?>"><i class="bi <?= $flash['type']==='success'?'bi-check-circle':'bi-exclamation-circle' ?>"></i> <?= e($flash['message']) ?></div><?php endif; ?>
<?php if(!($priorityPage['ready']??false)): ?><section class="empty-state"><i class="bi bi-database-exclamation"></i><h2>Atualização de banco pendente</h2><p>Execute a migração <strong>20260730_023_service_desk_prioridades_workflow.sql</strong>.</p></section><?php else: ?>
<section class="priority-summary"><?php foreach(array_slice($rows,0,5) as $priority): ?><article style="--priority-color:<?= e($priority['cor']) ?>"><strong><?= e($priority['codigo']) ?></strong><span><?= e($priority['nome']) ?></span><small><?= service_priority_duration((int)$priority['sla_primeira_interacao_minutos']) ?> para interagir · <?= service_priority_duration((int)$priority['sla_resolucao_minutos']) ?> para resolver</small></article><?php endforeach; ?></section>
<section class="panel"><form class="panel-head table-filters" method="get" action="<?= url('prioridades-service-desk') ?>"><div class="search"><span><i class="bi bi-search"></i></span><input type="search" name="q" value="<?= e($priorityPage['q']??'') ?>" placeholder="Buscar código, prioridade ou descrição..."></div><div class="panel-filters"><select name="status"><option value="">Todas as situações</option><option value="ativo" <?= ($priorityPage['status']??'')==='ativo'?'selected':'' ?>>Ativas</option><option value="inativo" <?= ($priorityPage['status']??'')==='inativo'?'selected':'' ?>>Inativas</option></select><button class="btn secondary"><i class="bi bi-search"></i> Buscar</button><?php if(($priorityPage['q']??'')!==''||($priorityPage['status']??'')!==''): ?><a class="btn secondary" href="<?= url('prioridades-service-desk') ?>" aria-label="Limpar filtros"><i class="bi bi-x-lg"></i></a><?php endif; ?></div></form>
<div class="table-wrap"><table><thead><tr><th>Prioridade</th><th>Primeira interação</th><th>Resolução</th><th>Uso</th><th>Situação</th><th>Ações</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="6"><div class="table-empty"><i class="bi bi-flag"></i><strong>Nenhuma prioridade encontrada</strong><span>Revise os filtros ou cadastre um nível de atendimento.</span></div></td></tr><?php endif; ?>
<?php foreach($rows as $row): $payload=['id'=>(int)$row['id'],'codigo'=>$row['codigo'],'nome'=>$row['nome'],'descricao'=>$row['descricao'],'cor'=>$row['cor'],'ordem'=>(int)$row['ordem'],'sla_primeira_interacao_minutos'=>(int)$row['sla_primeira_interacao_minutos'],'sla_resolucao_minutos'=>(int)$row['sla_resolucao_minutos'],'ativo'=>(int)$row['ativo']]; ?><tr><td><div class="priority-name"><span style="--priority-color:<?= e($row['cor']) ?>"><?= e($row['codigo']) ?></span><div><strong><?= e($row['nome']) ?></strong><small><?= e($row['descricao']?:'Sem descrição') ?></small></div></div></td><td><strong><?= service_priority_duration((int)$row['sla_primeira_interacao_minutos']) ?></strong></td><td><strong><?= service_priority_duration((int)$row['sla_resolucao_minutos']) ?></strong></td><td><strong><?= (int)$row['chamados'] ?> chamado(s)</strong><small><?= (int)$row['categorias'] ?> categoria(s)</small></td><td><span class="status <?= $row['ativo']?'active':'inactive' ?>"><?= $row['ativo']?'Ativa':'Inativa' ?></span></td><td><div class="row-actions"><?php if(can('service_priorities','update')): ?><button class="action-btn" data-priority-edit data-row="<?= e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?>" aria-label="Editar <?= e($row['codigo']) ?>"><i class="bi bi-pencil"></i></button><?php endif; ?><?php if(can('service_priorities','delete')): ?><button class="action-btn danger" data-priority-delete data-id="<?= (int)$row['id'] ?>" data-name="<?= e($row['codigo'].' · '.$row['nome']) ?>" aria-label="Excluir"><i class="bi bi-trash"></i></button><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div>
<?php $page=$priorityPage['page'];$perPage=$priorityPage['per_page'];$offset=$priorityPage['offset'];$totalRows=$priorityPage['total'];$totalPages=$priorityPage['pages']; ?><div class="pagination"><form method="get" action="<?= url('prioridades-service-desk') ?>" class="per-page"><input type="hidden" name="q" value="<?= e($priorityPage['q']) ?>"><input type="hidden" name="status" value="<?= e($priorityPage['status']) ?>"><label>Mostrar <select name="per_page" onchange="this.form.submit()"><?php foreach([5,10,25,50] as $size): ?><option value="<?= $size ?>" <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select> linhas</label></form><span>Mostrando <?= $totalRows?$offset+1:0 ?>–<?= min($offset+$perPage,$totalRows) ?> de <?= $totalRows ?></span><nav class="page-buttons"><?php if($page>1): ?><a href="<?= page_url('prioridades-service-desk',['page'=>$page-1]) ?>"><i class="bi bi-chevron-left"></i></a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++): ?><a class="<?= $p===$page?'active':'' ?>" href="<?= page_url('prioridades-service-desk',['page'=>$p]) ?>"><?= $p ?></a><?php endfor; ?><?php if($page<$totalPages): ?><a href="<?= page_url('prioridades-service-desk',['page'=>$page+1]) ?>"><i class="bi bi-chevron-right"></i></a><?php endif; ?></nav></div></section>

<div class="modal" id="priority-modal" aria-hidden="true"><div class="modal-dialog"><button class="modal-close" data-modal-close aria-label="Fechar"><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="eyebrow blue">Política de atendimento</span><h2 data-priority-title>Nova prioridade</h2><p>Os SLAs começam na criação do chamado e ficam congelados no ticket para preservar a auditoria.</p><form method="post" data-priority-form><?= csrf_field() ?><input type="hidden" name="action" value="create"><input type="hidden" name="id"><div class="form-grid"><label>Código<input name="codigo" required maxlength="5" placeholder="P1"></label><label>Nome<input name="nome" required maxlength="80" placeholder="Crítica"></label><label>Ordem<input type="number" name="ordem" min="1" max="99" value="3" required></label><label>Cor<input type="color" name="cor" value="#64748b"></label><label>Primeira interação (minutos)<input type="number" name="sla_primeira_interacao_minutos" min="1" max="525600" value="240" required></label><label>Resolução (minutos)<input type="number" name="sla_resolucao_minutos" min="1" max="525600" value="1440" required></label><label class="full">Descrição<textarea name="descricao" rows="3" maxlength="500"></textarea></label><label class="check full"><input type="checkbox" name="ativo" checked> Prioridade ativa</label></div><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn primary"><i class="bi bi-check-lg"></i> Salvar prioridade</button></div></form></div></div></div>
<div class="modal" id="delete-priority-modal" aria-hidden="true"><div class="modal-dialog confirm-dialog"><button class="modal-close" data-modal-close><i class="bi bi-x-lg"></i></button><div class="modal-content"><span class="confirm-icon"><i class="bi bi-trash"></i></span><h2>Excluir prioridade?</h2><p>Prioridades usadas em chamados ou categorias não podem ser excluídas. Item: <strong data-delete-priority-name></strong>.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" data-delete-priority-id><div class="modal-actions"><button type="button" class="btn secondary" data-modal-close>Cancelar</button><button class="btn danger">Excluir</button></div></form></div></div></div>
<?php endif; ?>
