<!doctype html><html lang="pt-BR"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#001e50">
<title><?= e($pageTitle) ?> · Drive Learn</title>
<link rel="icon" type="image/svg+xml" href="<?= url('public/assets/images/favicon.svg') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/images/favicon.svg') ?: 1) ?>"><link rel="shortcut icon" href="<?= url('public/assets/images/favicon.svg') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/images/favicon.svg') ?: 1) ?>">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
<link rel="stylesheet" href="<?= url('public/assets/css/main.css') ?>"><link rel="stylesheet" href="<?= url('public/assets/css/cards.css') ?>"><link rel="stylesheet" href="<?= url('public/assets/css/dashboard.css') ?>"><link rel="stylesheet" href="<?= url('public/assets/css/tables.css') ?>"><link rel="stylesheet" href="<?= url('public/assets/css/modals.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/modals.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/access.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/access.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/user-access-guard.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/user-access-guard.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/profile-images.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/profile-images.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/fleet.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/fleet.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/library.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/library.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/library-player-controls.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/library-player-controls.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/video-modal-fix.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/video-modal-fix.css') ?: 1) ?>"><link rel="stylesheet" href="<?= url('public/assets/css/reports.css') ?>?v=<?= (int)(@filemtime(__DIR__.'/../../public/assets/css/reports.css') ?: 1) ?>">
</head><body>
<div class="app-shell">
<aside class="sidebar" id="sidebar">
    <div class="sidebar-head"><a href="<?= url('dashboard') ?>" class="brand-lockup"><span class="brand-mark">VW</span><span>Drive Learn<small>Caminhões e Ônibus</small></span></a><button class="icon-btn close-menu" data-menu aria-label="Fechar menu"><i class="bi bi-x-lg" aria-hidden="true"></i></button></div>
    <nav class="nav"><span class="nav-label">Principal</span>
        <?php if(can('dashboard')): ?><a class="<?= $route===''||$route==='dashboard'?'active':'' ?>" href="<?= url('dashboard') ?>"><i class="bi bi-grid-1x2"></i> Visão geral</a><?php endif; ?>
        <?php if(can('library')): ?><a class="<?= $route==='biblioteca'?'active':'' ?>" href="<?= url('biblioteca') ?>"><i class="bi bi-play-circle"></i> Treinamentos</a><?php endif; ?>
        <?php if(can('fleet')): ?><a class="<?= $route==='frota'?'active':'' ?>" href="<?= url('frota') ?>"><i class="bi bi-truck"></i> Minha frota</a><?php endif; ?>
        <?php if(can('families')||can('models')||can('categories')||can('subcategories')||can('videos')||can('emission_standards')): ?><span class="nav-label">Gestão de conteúdo</span><?php endif; ?>
        <?php if(can('families')): ?><a class="<?= $route==='familias'?'active':'' ?>" href="<?= url('familias') ?>"><i class="bi bi-collection"></i> Famílias</a><?php endif; ?><?php if(can('models')): ?><a class="<?= $route==='modelos'?'active':'' ?>" href="<?= url('modelos') ?>"><i class="bi bi-truck-front"></i> Modelos</a><?php endif; ?><?php if(can('categories')): ?><a class="<?= $route==='categorias'?'active':'' ?>" href="<?= url('categorias') ?>"><i class="bi bi-grid"></i> Categorias</a><?php endif; ?><?php if(can('subcategories')): ?><a class="<?= $route==='subcategorias'?'active':'' ?>" href="<?= url('subcategorias') ?>"><i class="bi bi-diagram-3"></i> Subcategorias</a><?php endif; ?><?php if(can('videos')): ?><a class="<?= $route==='videos'?'active':'' ?>" href="<?= url('videos') ?>"><i class="bi bi-camera-video"></i> Vídeos</a><?php endif; ?><?php if(can('emission_standards')): ?><a class="<?= $route==='normas-emissoes'?'active':'' ?>" href="<?= url('normas-emissoes') ?>"><i class="bi bi-cloud-haze2"></i> Normas de emissões</a><?php endif; ?>
        <?php if(can('organizations')||can('clients')||can('users')||can('permissions')||can('reports')): ?><span class="nav-label">Administração</span><?php endif; ?><?php if(can('organizations')): ?><a class="<?= $route==='empresas-vwco'?'active':'' ?>" href="<?= url('empresas-vwco') ?>"><i class="bi bi-building-gear"></i> Empresas VWCO</a><?php endif; ?><?php if(can('clients')): ?><a class="<?= $route==='clientes'?'active':'' ?>" href="<?= url('clientes') ?>"><i class="bi bi-buildings"></i> Clientes</a><?php endif; ?><?php if(can('users')): ?><a class="<?= $route==='usuarios'?'active':'' ?>" href="<?= url('usuarios') ?>"><i class="bi bi-people"></i> Usuários</a><?php endif; ?><?php if(can('permissions')): ?><a class="<?= $route==='permissoes'?'active':'' ?>" href="<?= url('permissoes') ?>"><i class="bi bi-shield-lock"></i> Perfis e acessos</a><?php endif; ?><?php if(can('reports')): ?><a class="<?= $route==='relatorios'?'active':'' ?>" href="<?= url('relatorios') ?>"><i class="bi bi-bar-chart"></i> Relatórios</a><?php endif; ?>
    </nav>
    <div class="sidebar-help"><strong>Central de ajuda</strong><span>Encontre respostas ou fale com o suporte.</span><a href="#">Acessar suporte <i class="bi bi-arrow-right"></i></a></div>
</aside>
<div class="sidebar-backdrop" data-menu></div>
<div class="main-area"><header class="topbar"><button class="icon-btn hamburger" data-menu aria-label="Abrir menu"><i class="bi bi-list" aria-hidden="true"></i></button><div class="top-title with-context"><div><span><?= e($pageTitle) ?></span><small><?= e(user()['active_company_name'] ?? 'Volkswagen Caminhões e Ônibus') ?></small></div><?php if(count(user()['companies']??[])>1): ?><form class="company-context" method="post" action="<?= url('empresa-ativa') ?>"><?= csrf_field() ?><i class="bi bi-buildings"></i><select name="empresa_id" onchange="this.form.submit()" aria-label="Empresa ativa"><?php foreach(user()['companies'] as $company): ?><option value="<?= (int)$company['id'] ?>" <?= (int)$company['id']===(int)(user()['active_company_id']??0)?'selected':'' ?>><?= e($company['nome']) ?></option><?php endforeach; ?></select></form><?php endif; ?></div><div class="top-actions"><button class="icon-btn notification" aria-label="Notificações"><i class="bi bi-bell" aria-hidden="true"></i><b>3</b></button><div class="user-menu"><span class="avatar"><?php if(user()['foto']??null): ?><img src="<?= url(user()['foto']) ?>" alt="Foto de <?= e(user()['nome']??'Usuário') ?>"><?php else: ?><?= e(strtoupper(substr(user()['nome'] ?? 'U',0,2))) ?><?php endif; ?></span><div><strong><?= e(ucfirst(user()['nome'] ?? 'Usuário')) ?></strong><small><?= e(user()['role_name'] ?? '') ?></small></div><button class="icon-btn" data-user-menu aria-label="Abrir menu do usuário"><i class="bi bi-chevron-down" aria-hidden="true"></i></button><div class="user-dropdown"><form method="post" action="<?= url('logout') ?>"><?= csrf_field() ?><button type="submit"><i class="bi bi-box-arrow-right"></i> Sair da conta</button></form></div></div></div></header>
<main class="content">
